"""Persistent registry for validated generated coding projects.

The BMAD workflow publishes the latest accepted artifact to ``workspace/`` for
quick manual testing.  This module additionally snapshots each accepted project
under ``workspace/projects/<project_id>/`` with a ``project_manifest.json``.

Titan memory should store a compact reference to the project, not the full code:
project id, path, prompt, main functions, QA status and manual commands.  The
agent can later retrieve that memory, open the project folder and reuse or
modify the generated files instead of starting from scratch.
"""

from __future__ import annotations

import ast
import hashlib
import json
import re
import shutil
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Sequence

from tools.file_tools import WORKSPACE_DIR, ensure_coding_dirs

PROJECTS_DIR = WORKSPACE_DIR / "projects"
PROJECT_INDEX_PATH = PROJECTS_DIR / "project_index.json"
MANIFEST_NAME = "project_manifest.json"


@dataclass(frozen=True)
class GeneratedProjectManifest:
    """Metadata describing one validated generated project."""

    project_id: str
    original_prompt: str
    project_kind: str
    project_path: str
    files: list[str]
    main_functions: list[str]
    manual_test_commands: list[str]
    unit_test_command: str | None
    qa_status: str
    docker_status: str
    created_at: str
    updated_at: str
    source: str = "bmad_coding_team"
    code_hash: str | None = None
    memory_summary: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def ensure_project_registry() -> None:
    ensure_coding_dirs()
    PROJECTS_DIR.mkdir(parents=True, exist_ok=True)
    if not PROJECT_INDEX_PATH.exists():
        PROJECT_INDEX_PATH.write_text("[]\n", encoding="utf-8")


def _slugify(text: str, default: str = "generated_project") -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "_", text.strip().lower()).strip("_")
    return (slug or default)[:56]


def _short_hash(text: str) -> str:
    return hashlib.sha1(text.encode("utf-8", errors="replace")).hexdigest()[:10]


def _read_index() -> list[dict[str, Any]]:
    ensure_project_registry()
    try:
        data = json.loads(PROJECT_INDEX_PATH.read_text(encoding="utf-8"))
        return data if isinstance(data, list) else []
    except Exception:
        return []


def _write_index(index: list[dict[str, Any]]) -> None:
    ensure_project_registry()
    PROJECT_INDEX_PATH.write_text(json.dumps(index, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def _extract_python_functions(path: Path) -> list[str]:
    if not path.exists() or path.suffix != ".py":
        return []
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except Exception:
        return []
    names = [node.name for node in tree.body if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))]
    return names[:30]


def _read_project_app_text(project_dir: Path) -> str:
    app_path = project_dir / "app.py"
    if not app_path.exists() or not app_path.is_file():
        return ""
    try:
        return app_path.read_text(encoding="utf-8", errors="replace")
    except Exception:
        return ""


def is_weak_generic_project_archive(
    *,
    project_kind: str,
    main_functions: Sequence[str] | None,
    app_text: str,
    files: Sequence[str] | None = None,
) -> bool:
    """Return True when an archive is only a weak placeholder project.

    These archives are harmful for long-term memory because they look validated
    while containing no useful implementation.  A typical bad output is the old
    fallback with only ``describe_project()`` and ``main()``.
    """

    functions = {str(name).strip() for name in (main_functions or []) if str(name).strip()}
    app_lower = (app_text or "").lower()
    file_set = {str(name).replace("\\", "/") for name in (files or [])}
    if not app_text.strip():
        return True
    if not {"app.py", "README.md"}.issubset(file_set):
        return True
    placeholder_markers = (
        "return a small structured description",
        "generated by the minimal bmad coding team",
        "build a useful generic python cli",
        "describe_project()",
        "def describe_project",
        "goal:",
    )
    has_placeholder_text = any(marker in app_lower for marker in placeholder_markers)
    only_placeholder_functions = bool(functions) and functions.issubset({"describe_project", "main"})
    explicit_generic_kind = str(project_kind or "").strip().lower() in {"generic", "generated_project"}
    return bool((explicit_generic_kind and only_placeholder_functions) or (only_placeholder_functions and has_placeholder_text))


def _index_item_from_manifest(manifest: dict[str, Any]) -> dict[str, Any]:
    return {
        "project_id": manifest.get("project_id", ""),
        "project_kind": manifest.get("project_kind", ""),
        "original_prompt": manifest.get("original_prompt", ""),
        "project_path": manifest.get("project_path", ""),
        "created_at": manifest.get("created_at", ""),
        "qa_status": manifest.get("qa_status", ""),
        "files": list(manifest.get("files") or []),
        "main_functions": list(manifest.get("main_functions") or []),
    }


def iter_project_manifests() -> list[dict[str, Any]]:
    """Read all valid project manifests from ``workspace/projects``."""

    ensure_project_registry()
    manifests: list[dict[str, Any]] = []
    for manifest_path in sorted(PROJECTS_DIR.glob(f"*/{MANIFEST_NAME}")):
        try:
            data = json.loads(manifest_path.read_text(encoding="utf-8"))
        except Exception:
            continue
        if isinstance(data, dict) and data.get("project_id"):
            manifests.append(data)
    return manifests


def rebuild_project_index(*, exclude_weak_generic: bool = True) -> dict[str, Any]:
    """Rebuild ``project_index.json`` from manifests that still exist on disk."""

    manifests = iter_project_manifests()
    rebuilt: list[dict[str, Any]] = []
    skipped_weak: list[str] = []
    seen: set[str] = set()
    for manifest in manifests:
        project_id = str(manifest.get("project_id") or "")
        if not project_id or project_id in seen:
            continue
        seen.add(project_id)
        project_path = WORKSPACE_DIR.parent / str(manifest.get("project_path", ""))
        app_text = _read_project_app_text(project_path)
        if exclude_weak_generic and is_weak_generic_project_archive(
            project_kind=str(manifest.get("project_kind") or ""),
            main_functions=manifest.get("main_functions") or [],
            app_text=app_text,
            files=manifest.get("files") or [],
        ):
            skipped_weak.append(project_id)
            continue
        rebuilt.append(_index_item_from_manifest(manifest))
    rebuilt.sort(key=lambda item: str(item.get("created_at", "")))
    _write_index(rebuilt)
    return {
        "status": "ok",
        "manifests_found": len(manifests),
        "index_entries_written": len(rebuilt),
        "weak_generic_archives_skipped": skipped_weak,
        "index_path": PROJECT_INDEX_PATH.as_posix(),
    }


def project_integrity_status() -> dict[str, Any]:
    """Compare archive folders, manifests and project index entries."""

    ensure_project_registry()
    index = _read_index()
    manifests = iter_project_manifests()
    manifest_by_id = {str(m.get("project_id")): m for m in manifests if m.get("project_id")}
    index_ids = [str(item.get("project_id")) for item in index if item.get("project_id")]
    manifest_ids = sorted(manifest_by_id)
    missing_manifest_ids = [pid for pid in index_ids if pid not in manifest_by_id]
    missing_index_ids = [pid for pid in manifest_ids if pid not in set(index_ids)]
    weak_generic_ids: list[str] = []
    duplicate_code_hashes: dict[str, list[str]] = {}
    for project_id, manifest in manifest_by_id.items():
        project_path = WORKSPACE_DIR.parent / str(manifest.get("project_path", ""))
        if is_weak_generic_project_archive(
            project_kind=str(manifest.get("project_kind") or ""),
            main_functions=manifest.get("main_functions") or [],
            app_text=_read_project_app_text(project_path),
            files=manifest.get("files") or [],
        ):
            weak_generic_ids.append(project_id)
        code_hash = str(manifest.get("code_hash") or "")
        if code_hash:
            duplicate_code_hashes.setdefault(code_hash, []).append(project_id)
    duplicate_code_hashes = {h: ids for h, ids in duplicate_code_hashes.items() if len(ids) > 1}
    ok = not missing_manifest_ids and not missing_index_ids and not weak_generic_ids
    return {
        "ok": ok,
        "projects_dir": PROJECTS_DIR.as_posix(),
        "index_path": PROJECT_INDEX_PATH.as_posix(),
        "index_entries": len(index),
        "manifests": len(manifests),
        "missing_manifest_ids": missing_manifest_ids,
        "missing_index_ids": missing_index_ids,
        "weak_generic_archive_ids": sorted(weak_generic_ids),
        "duplicate_code_hashes": duplicate_code_hashes,
    }


def format_project_integrity_report() -> str:
    """Return a readable project archive integrity report."""

    status = project_integrity_status()
    lines = ["Project archive integrity:"]
    lines.append(f"- ok: {status['ok']}")
    lines.append(f"- index_entries: {status['index_entries']}")
    lines.append(f"- manifests_on_disk: {status['manifests']}")
    if status["missing_manifest_ids"]:
        lines.append("- index entries without manifest: " + ", ".join(status["missing_manifest_ids"]))
    if status["missing_index_ids"]:
        lines.append("- manifests missing from index: " + ", ".join(status["missing_index_ids"]))
    if status["weak_generic_archive_ids"]:
        lines.append("- weak generic archives: " + ", ".join(status["weak_generic_archive_ids"]))
    duplicates = status.get("duplicate_code_hashes") or {}
    if duplicates:
        lines.append("- duplicate code hashes:")
        for code_hash, ids in duplicates.items():
            lines.append(f"  - {code_hash}: {', '.join(ids)}")
    lines.append(f"- projects_dir: {status['projects_dir']}")
    lines.append(f"- index_path: {status['index_path']}")
    return "\n".join(lines)

def _copy_workspace_files(project_dir: Path, files: Sequence[str]) -> list[str]:
    copied: list[str] = []
    for relative in files:
        rel = Path(str(relative).replace("\\", "/"))
        if rel.is_absolute() or ".." in rel.parts or not rel.parts:
            continue
        if rel.parts[0] == "projects":
            continue
        source = WORKSPACE_DIR / rel
        if not source.exists() or not source.is_file():
            continue
        destination = project_dir / rel
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)
        copied.append(rel.as_posix())
    return sorted(copied)


def archive_generated_project(
    *,
    task: str,
    project_kind: str,
    workspace_files: Sequence[str],
    qa_passed: bool,
    docker_output: str | None = None,
    manual_test_commands: Sequence[str] | None = None,
    unit_test_command: str | None = "cd workspace; python -m unittest test_app.py; cd ..",
    metadata: dict[str, Any] | None = None,
) -> GeneratedProjectManifest:
    """Snapshot a validated workspace artifact into ``workspace/projects``.

    The archive is intentionally created after publication, because only
    published files have passed QA and Evaluator review.
    """

    ensure_project_registry()
    now = datetime.now(timezone.utc).isoformat(timespec="seconds")
    base_slug = _slugify(project_kind if project_kind != "generic" else task)
    project_id = f"{base_slug}_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}_{_short_hash(task)}"
    project_dir = PROJECTS_DIR / project_id
    project_dir.mkdir(parents=True, exist_ok=False)

    copied_files = _copy_workspace_files(project_dir, workspace_files)
    app_path = project_dir / "app.py"
    functions = _extract_python_functions(app_path)
    code_hash = None
    app_text = ""
    if app_path.exists():
        app_text = app_path.read_text(encoding="utf-8", errors="replace")
        code_hash = _short_hash(app_text)

    if is_weak_generic_project_archive(
        project_kind=project_kind,
        main_functions=functions,
        app_text=app_text,
        files=copied_files,
    ):
        shutil.rmtree(project_dir, ignore_errors=True)
        raise ValueError(
            "weak_generic_project_refused: generated project contains only a placeholder generic CLI; "
            "it was not archived or indexed"
        )

    docker_status = "not_run"
    if docker_output:
        lower = docker_output.lower()
        if "skipped" in lower:
            docker_status = "skipped"
        elif "failed" in lower or "error" in lower:
            docker_status = "failed"
        else:
            docker_status = "passed"

    manifest = GeneratedProjectManifest(
        project_id=project_id,
        original_prompt=task,
        project_kind=project_kind,
        project_path=project_dir.relative_to(WORKSPACE_DIR.parent).as_posix(),
        files=copied_files,
        main_functions=functions,
        manual_test_commands=list(manual_test_commands or []),
        unit_test_command=unit_test_command,
        qa_status="passed" if qa_passed else "failed",
        docker_status=docker_status,
        created_at=now,
        updated_at=now,
        code_hash=code_hash,
        memory_summary=build_project_memory_summary(
            project_id=project_id,
            task=task,
            project_kind=project_kind,
            project_path=project_dir.relative_to(WORKSPACE_DIR.parent).as_posix(),
            files=copied_files,
            functions=functions,
            qa_status="passed" if qa_passed else "failed",
            manual_test_commands=list(manual_test_commands or []),
        ),
        metadata=dict(metadata or {}),
    )
    (project_dir / MANIFEST_NAME).write_text(json.dumps(manifest.to_dict(), indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    index = _read_index()
    index = [item for item in index if item.get("project_id") != manifest.project_id]
    index.append(_index_item_from_manifest(manifest.to_dict()))
    _write_index(index)
    return manifest


def build_project_memory_summary(
    *,
    project_id: str,
    task: str,
    project_kind: str,
    project_path: str,
    files: Sequence[str],
    functions: Sequence[str],
    qa_status: str,
    manual_test_commands: Sequence[str],
) -> str:
    functions_text = ", ".join(functions) if functions else "unknown functions"
    files_text = ", ".join(files) if files else "no files"
    commands_text = "; ".join(manual_test_commands[:3]) if manual_test_commands else "see README.md"
    return (
        f"Validated generated project {project_id}: kind={project_kind}; prompt={task!r}; "
        f"path={project_path}; files={files_text}; main_functions={functions_text}; "
        f"QA={qa_status}; manual_tests={commands_text}."
    )


def list_generated_projects(limit: int = 20) -> str:
    """Return a readable list of archived generated projects."""

    index = _read_index()
    if not index:
        return "No generated project archives found."
    rows = index[-limit:]
    lines = [f"Generated project archives ({len(rows)} shown / {len(index)} total):"]
    for item in reversed(rows):
        functions = ", ".join(item.get("main_functions") or []) or "functions unknown"
        lines.append(
            f"- {item.get('project_id')} [{item.get('project_kind')}] "
            f"QA={item.get('qa_status')} path={item.get('project_path')} functions={functions}"
        )
    return "\n".join(lines)


def read_project_manifest(project_id: str) -> dict[str, Any] | None:
    """Read one project manifest by id."""

    safe_id = _slugify(project_id, default="")
    if not safe_id:
        return None
    manifest_path = PROJECTS_DIR / safe_id / MANIFEST_NAME
    if not manifest_path.exists():
        return None
    try:
        data = json.loads(manifest_path.read_text(encoding="utf-8"))
        return data if isinstance(data, dict) else None
    except Exception:
        return None



def _project_search_score(item: dict[str, Any], query: str) -> int:
    """Simple deterministic score for matching a user request to archived projects."""

    query_words = set(re.findall(r"[a-zA-Z0-9_]{3,}", (query or "").lower()))
    if not query_words:
        return 0
    haystack_parts = [
        str(item.get("project_id", "")),
        str(item.get("project_kind", "")),
        str(item.get("original_prompt", "")),
        " ".join(str(x) for x in item.get("files", []) or []),
        " ".join(str(x) for x in item.get("main_functions", []) or []),
    ]
    haystack = " ".join(haystack_parts).lower()
    score = 0
    for word in query_words:
        if word in haystack:
            score += 2
    # Strong boosts for common semantic aliases.
    aliases = {
        "quadratic": ["quadratic", "solve_quadratic", "discriminant", "roots"],
        "equation": ["quadratic", "solve_quadratic", "discriminant"],
        "csv": ["csv", "statistics", "calculate_statistics"],
        "memory": ["memory", "memories", "store_memory", "retrieve"],
        "todo": ["todo", "task"],
        "email": ["email", "phone", "validator"],
        "phone": ["email", "phone", "validator"],
        "caesar": ["caesar", "cipher", "encrypt", "decrypt"],
        "cipher": ["caesar", "cipher", "encrypt", "decrypt"],
        "organize": ["organizer", "extension", "files"],
        "files": ["organizer", "extension", "files"],
    }
    for word in query_words:
        for alias in aliases.get(word, []):
            if alias in haystack:
                score += 3
    return score



def extract_project_id_from_text(text: str) -> str | None:
    """Return an archived project id mentioned explicitly in free text."""

    query = str(text or "")
    if not query.strip():
        return None
    index = _read_index()
    ids = [str(item.get("project_id")) for item in index if item.get("project_id")]
    # Prefer longest ids first so a short partial id cannot steal a longer match.
    for project_id in sorted(ids, key=len, reverse=True):
        if project_id and project_id in query:
            return project_id
    # Also accept the last 8+ chars of a project id for terminal convenience.
    tokens = set(re.findall(r"[a-zA-Z0-9_\-]{8,}", query))
    for project_id in ids:
        for token in tokens:
            if token and project_id.endswith(token):
                return project_id
    return None


def find_generated_projects(query: str, limit: int = 5) -> list[dict[str, Any]]:
    """Find archived projects relevant to a natural-language query.

    Exact project-id references are prioritized over fuzzy search. This makes
    commands such as ``modify project quadratic_solver_...`` deterministic and
    prevents the agent from accidentally modifying a similarly named archive.
    """

    index = _read_index()
    explicit_id = extract_project_id_from_text(query)
    if explicit_id:
        exact = [dict(item) | {"match_score": 10_000, "match_reason": "explicit_project_id"} for item in index if str(item.get("project_id")) == explicit_id]
        if exact:
            return exact[: max(0, int(limit))]

    scored: list[tuple[int, dict[str, Any]]] = []
    for item in index:
        score = _project_search_score(item, query)
        if score > 0:
            scored.append((score, item))
    scored.sort(key=lambda pair: (pair[0], str(pair[1].get("created_at", ""))), reverse=True)
    return [dict(item) | {"match_score": score} for score, item in scored[: max(0, int(limit))]]


def format_project_search_results(query: str, limit: int = 5) -> str:
    """Return readable project search results for the chat interface."""

    matches = find_generated_projects(query, limit=limit)
    if not matches:
        return f"No generated project archive matched: {query!r}"
    lines = [f"Generated project matches for {query!r}:"]
    for item in matches:
        functions = ", ".join(item.get("main_functions") or []) or "functions unknown"
        lines.append(
            f"- {item.get('project_id')} [{item.get('project_kind')}] "
            f"score={item.get('match_score')} QA={item.get('qa_status')} "
            f"path={item.get('project_path')} functions={functions}"
        )
    return "\n".join(lines)


def format_project_detail(project_id: str) -> str:
    """Return readable details for one archived project."""

    manifest = read_project_manifest(project_id)
    if not manifest:
        return f"No project manifest found for: {project_id}"
    lines = [f"Generated project: {manifest.get('project_id')}"]
    lines.append(f"- kind: {manifest.get('project_kind')}")
    lines.append(f"- path: {manifest.get('project_path')}")
    lines.append(f"- prompt: {manifest.get('original_prompt')}")
    lines.append(f"- QA: {manifest.get('qa_status')} | Docker: {manifest.get('docker_status')}")
    lines.append("- files: " + (", ".join(manifest.get("files") or []) or "none"))
    lines.append("- functions: " + (", ".join(manifest.get("main_functions") or []) or "unknown"))
    commands = manifest.get("manual_test_commands") or []
    if commands:
        lines.append("Manual test commands:")
        lines.extend(f"- {command}" for command in commands)
    return "\n".join(lines)



def format_project_file_preview(project_id: str, relative_path: str, max_chars: int = 4000) -> str:
    """Return a readable preview of one file from an archived project."""

    content = read_project_file(project_id, relative_path)
    if content is None:
        return f"No readable file {relative_path!r} found for project: {project_id}"
    trimmed = content[:max(0, int(max_chars))]
    if len(content) > len(trimmed):
        trimmed += "\n... [truncated]"
    return f"Archived file preview: {project_id}/{relative_path}\n" + trimmed


def read_project_file(project_id: str, relative_path: str) -> str | None:
    """Read one safe file from an archived project."""

    manifest = read_project_manifest(project_id)
    if not manifest:
        return None
    rel = Path(str(relative_path).replace("\\", "/"))
    if rel.is_absolute() or ".." in rel.parts or not rel.parts:
        return None
    project_path = WORKSPACE_DIR.parent / str(manifest.get("project_path", ""))
    target = project_path / rel
    try:
        if not target.is_file():
            return None
        return target.read_text(encoding="utf-8", errors="replace")
    except Exception:
        return None



def restore_project_to_staging(project_id: str, *, files: Sequence[str] | None = None) -> dict[str, Any]:
    """Copy a validated archived project back into staging for reuse/modification.

    The archive remains immutable. The staged copy can be modified, tested,
    published and archived as a new version with metadata pointing to the
    parent project.
    """

    from tools.file_tools import STAGING_DIR, clear_staging

    manifest = read_project_manifest(project_id)
    if not manifest:
        return {"ok": False, "project_id": project_id, "error": "manifest_not_found", "copied_files": []}

    requested_files = list(files or manifest.get("files") or [])
    clear_staging()
    copied: list[str] = []
    project_path = WORKSPACE_DIR.parent / str(manifest.get("project_path", ""))
    for relative in requested_files:
        rel = Path(str(relative).replace("\\", "/"))
        if rel.is_absolute() or ".." in rel.parts or not rel.parts:
            continue
        source = project_path / rel
        if not source.is_file():
            continue
        destination = STAGING_DIR / rel
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)
        copied.append(rel.as_posix())

    return {
        "ok": bool(copied),
        "project_id": str(manifest.get("project_id")),
        "project_path": str(manifest.get("project_path")),
        "project_kind": str(manifest.get("project_kind")),
        "copied_files": sorted(copied),
    }


def select_project_for_reuse(query: str) -> dict[str, Any] | None:
    """Return the best archived project candidate for a modification request."""

    matches = find_generated_projects(query, limit=1)
    return matches[0] if matches else None

def build_project_reuse_context(query: str, limit: int = 3, max_chars_per_file: int = 1800) -> str:
    """Build compact context that lets BMAD reuse existing validated projects.

    This context is intentionally a summary plus short file previews.  Titan or
    the LLM should not receive entire large files by default; the manifest path
    remains the stable pointer for future deeper reuse.
    """

    matches = find_generated_projects(query, limit=limit)
    if not matches:
        return ""
    blocks: list[str] = ["Relevant generated project archives that may be reused:"]
    for item in matches:
        project_id = str(item.get("project_id"))
        manifest = read_project_manifest(project_id) or item
        blocks.append(
            f"Project {project_id}: kind={manifest.get('project_kind')}; "
            f"path={manifest.get('project_path')}; QA={manifest.get('qa_status')}; "
            f"functions={', '.join(manifest.get('main_functions') or []) or 'unknown'}; "
            f"prompt={manifest.get('original_prompt')!r}."
        )
        for filename in ["README.md", "app.py", "test_app.py"]:
            if filename not in (manifest.get("files") or []):
                continue
            content = read_project_file(project_id, filename)
            if not content:
                continue
            preview = content[:max_chars_per_file]
            if len(content) > max_chars_per_file:
                preview += "\n... [truncated]"
            blocks.append(f"--- {project_id}/{filename} preview ---\n{preview}")
    return "\n\n".join(blocks)
