#!/usr/bin/env python3
"""Deterministic BMAD code templates for common Python CLI requests.

These templates are intentionally small and standard-library only. They give the
BMAD workflow a strong offline fallback for frequent coding prompts while the
LLM path remains responsible for open-ended requests outside these patterns.
"""

from __future__ import annotations

import json
from typing import Any


def _request(spec: Any) -> str:
    return str(getattr(spec, "original_request", "") or "")


def _json(text: str) -> str:
    return json.dumps(text, ensure_ascii=False)


def build_app_template(project_kind: str, spec: Any) -> str | None:
    builders = {
        "memory_store": _memory_store_app,
        "csv_statistics": _csv_statistics_app,
        "multi_agent_simulation": _multi_agent_app,
        "email_phone_validator": _email_phone_validator_app,
        "file_organizer": _file_organizer_app,
        "caesar_cipher": _caesar_cipher_app,
        "chatbot_with_memory": _chatbot_memory_app,
        "test_runner": _test_runner_app,
        "calculator_cli": _calculator_app,
        "text_analyzer": _text_analyzer_app,
    }
    builder = builders.get(project_kind)
    return builder(spec) if builder else None


def build_test_template(project_kind: str, spec: Any) -> str | None:
    builders = {
        "memory_store": _memory_store_test,
        "csv_statistics": _csv_statistics_test,
        "multi_agent_simulation": _multi_agent_test,
        "email_phone_validator": _email_phone_validator_test,
        "file_organizer": _file_organizer_test,
        "caesar_cipher": _caesar_cipher_test,
        "chatbot_with_memory": _chatbot_memory_test,
        "test_runner": _test_runner_test,
        "calculator_cli": _calculator_test,
        "text_analyzer": _text_analyzer_test,
    }
    builder = builders.get(project_kind)
    return builder(spec) if builder else None


def _memory_store_app(spec: Any) -> str:
    request = _json(_request(spec))
    return f'''"""Small user-memory store CLI generated by BMAD."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

REQUEST = {request}
DEFAULT_MEMORY_FILE = Path("memories.json")


def load_memories(path: Path = DEFAULT_MEMORY_FILE) -> dict[str, list[str]]:
    if not path.exists():
        return {{}}
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError("Memory file must contain a JSON object.")
    return {{str(key): [str(item) for item in value] for key, value in data.items()}}


def save_memories(memories: dict[str, list[str]], path: Path = DEFAULT_MEMORY_FILE) -> None:
    path.write_text(json.dumps(memories, indent=2, ensure_ascii=False), encoding="utf-8")


def store_memory(user: str, memory: str, path: Path = DEFAULT_MEMORY_FILE) -> list[str]:
    user = user.strip()
    memory = memory.strip()
    if not user or not memory:
        raise ValueError("User and memory must not be empty.")
    memories = load_memories(path)
    memories.setdefault(user, []).append(memory)
    save_memories(memories, path)
    return memories[user]


def retrieve_memories(user: str, path: Path = DEFAULT_MEMORY_FILE) -> list[str]:
    return load_memories(path).get(user.strip(), [])


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Store and retrieve small user memories.")
    subparsers = parser.add_subparsers(dest="command", required=True)
    store = subparsers.add_parser("store", help="Store a memory for a user.")
    store.add_argument("user")
    store.add_argument("memory")
    retrieve = subparsers.add_parser("retrieve", help="Retrieve memories for a user.")
    retrieve.add_argument("user")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if args.command == "store":
        memories = store_memory(args.user, args.memory)
        print(f"Stored memory #{{len(memories)}} for {{args.user}}.")
    elif args.command == "retrieve":
        memories = retrieve_memories(args.user)
        if not memories:
            print(f"No memories found for {{args.user}}.")
        else:
            for index, memory in enumerate(memories, start=1):
                print(f"{{index}}. {{memory}}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def _memory_store_test(spec: Any) -> str:
    return '''import tempfile
import unittest
from pathlib import Path

from app import retrieve_memories, store_memory


class TestMemoryStore(unittest.TestCase):
    def test_store_and_retrieve_memory(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            path = Path(tmpdir) / "memories.json"
            store_memory("Elwen", "favorite color is violet", path)
            store_memory("Elwen", "likes AI projects", path)
            self.assertEqual(
                retrieve_memories("Elwen", path),
                ["favorite color is violet", "likes AI projects"],
            )

    def test_unknown_user_returns_empty_list(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            self.assertEqual(retrieve_memories("Unknown", Path(tmpdir) / "memories.json"), [])


if __name__ == "__main__":
    unittest.main()
'''


def _csv_statistics_app(spec: Any) -> str:
    request = _json(_request(spec))
    return f'''"""CSV statistics CLI generated by BMAD."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

REQUEST = {request}


def read_numeric_values(path: Path, column: str | None = None) -> list[float]:
    values: list[float] = []
    with path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        if reader.fieldnames is None:
            raise ValueError("CSV file must have a header row.")
        selected_column = column or next((name for name in reader.fieldnames if name.lower() in {{"score", "value", "amount", "number"}}), None)
        selected_column = selected_column or reader.fieldnames[-1]
        if selected_column not in reader.fieldnames:
            raise ValueError(f"Column {{selected_column!r}} not found in CSV file.")
        for row in reader:
            raw = (row.get(selected_column) or "").strip()
            if raw:
                values.append(float(raw))
    if not values:
        raise ValueError("No numeric values found.")
    return values


def calculate_statistics(values: list[float]) -> dict[str, float]:
    ordered = sorted(values)
    count = len(values)
    return {{
        "count": float(count),
        "min": ordered[0],
        "max": ordered[-1],
        "mean": sum(values) / count,
    }}


def format_statistics(stats: dict[str, float]) -> str:
    return "\\n".join([
        f"count: {{int(stats['count'])}}",
        f"min: {{stats['min']:.2f}}",
        f"max: {{stats['max']:.2f}}",
        f"mean: {{stats['mean']:.2f}}",
    ])


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Read a CSV file and calculate statistics for one numeric column.")
    parser.add_argument("csv_file", type=Path)
    parser.add_argument("--column", default=None, help="Numeric column to analyze. Defaults to score/value/last column.")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        values = read_numeric_values(args.csv_file, args.column)
        print(format_statistics(calculate_statistics(values)))
    except Exception as exc:
        print(f"Error: {{exc}}")
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def _csv_statistics_test(spec: Any) -> str:
    return '''import tempfile
import unittest
from pathlib import Path

from app import calculate_statistics, read_numeric_values


class TestCsvStatistics(unittest.TestCase):
    def test_read_values_and_calculate_statistics(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            path = Path(tmpdir) / "sample.csv"
            path.write_text("name,score\\nAlice,10\\nBob,15\\nCharlie,20\\n", encoding="utf-8")
            values = read_numeric_values(path, "score")
            self.assertEqual(values, [10.0, 15.0, 20.0])
            stats = calculate_statistics(values)
            self.assertEqual(stats["min"], 10.0)
            self.assertEqual(stats["max"], 20.0)
            self.assertEqual(stats["mean"], 15.0)


if __name__ == "__main__":
    unittest.main()
'''


def _multi_agent_app(spec: Any) -> str:
    request = _json(_request(spec))
    return f'''"""Simple multi-agent simulation generated by BMAD."""

from __future__ import annotations

import argparse
from dataclasses import dataclass

REQUEST = {request}


@dataclass(frozen=True)
class Agent:
    name: str
    role: str

    def respond(self, task: str) -> str:
        return f"{{self.name}}({{self.role}}) handled: {{task}}"


def run_simulation(task: str, agents: list[Agent] | None = None) -> list[str]:
    agents = agents or [Agent("Manager", "planning"), Agent("Developer", "implementation"), Agent("QA", "validation")]
    return [agent.respond(task) for agent in agents]


def summarize_simulation(task: str) -> str:
    lines = ["Multi-agent simulation:"]
    lines.extend(run_simulation(task))
    return "\\n".join(lines)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Simulate a tiny multi-agent workflow.")
    parser.add_argument("task", nargs="?", default="Build and test a feature")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    print(summarize_simulation(args.task))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def _multi_agent_test(spec: Any) -> str:
    return '''import unittest

from app import Agent, run_simulation, summarize_simulation


class TestMultiAgentSimulation(unittest.TestCase):
    def test_simulation_has_agent_responses(self) -> None:
        responses = run_simulation("ship code", [Agent("A", "plan"), Agent("B", "test")])
        self.assertEqual(len(responses), 2)
        self.assertIn("A(plan)", responses[0])

    def test_summary_mentions_multi_agent(self) -> None:
        self.assertIn("Multi-agent simulation", summarize_simulation("demo"))


if __name__ == "__main__":
    unittest.main()
'''


def _email_phone_validator_app(spec: Any) -> str:
    request = _json(_request(spec))
    return f'''"""Email and phone validator CLI generated by BMAD."""

from __future__ import annotations

import argparse
import re

REQUEST = {request}
EMAIL_RE = re.compile(r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{{2,}}$")
PHONE_RE = re.compile(r"^\\+?[0-9][0-9 .-]{{7,18}}[0-9]$")


def is_valid_email(value: str) -> bool:
    return bool(EMAIL_RE.fullmatch(value.strip()))


def is_valid_phone(value: str) -> bool:
    compact = re.sub(r"[ .-]", "", value.strip())
    return bool(PHONE_RE.fullmatch(value.strip())) and 8 <= len(compact.lstrip("+")) <= 15


def validate(kind: str, value: str) -> bool:
    if kind == "email":
        return is_valid_email(value)
    if kind == "phone":
        return is_valid_phone(value)
    raise ValueError("kind must be 'email' or 'phone'")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Validate email addresses and phone numbers.")
    parser.add_argument("kind", choices=["email", "phone"])
    parser.add_argument("value")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    ok = validate(args.kind, args.value)
    print("valid" if ok else "invalid")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
'''


def _email_phone_validator_test(spec: Any) -> str:
    return '''import unittest

from app import is_valid_email, is_valid_phone


class TestValidators(unittest.TestCase):
    def test_email_validation(self) -> None:
        self.assertTrue(is_valid_email("test@example.com"))
        self.assertFalse(is_valid_email("wrong-email"))

    def test_phone_validation(self) -> None:
        self.assertTrue(is_valid_phone("+33612345678"))
        self.assertFalse(is_valid_phone("abc123"))


if __name__ == "__main__":
    unittest.main()
'''


def _file_organizer_app(spec: Any) -> str:
    request = _json(_request(spec))
    return f'''"""File organizer CLI generated by BMAD."""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path

REQUEST = {request}


def extension_folder(path: Path) -> str:
    return path.suffix[1:].lower() if path.suffix else "no_extension"


def organize_by_extension(folder: Path) -> dict[str, int]:
    if not folder.exists() or not folder.is_dir():
        raise ValueError("Folder does not exist or is not a directory.")
    moved: dict[str, int] = {{}}
    for item in list(folder.iterdir()):
        if not item.is_file():
            continue
        name = extension_folder(item)
        target_dir = folder / name
        target_dir.mkdir(exist_ok=True)
        shutil.move(str(item), str(target_dir / item.name))
        moved[name] = moved.get(name, 0) + 1
    return moved


def format_result(result: dict[str, int]) -> str:
    if not result:
        return "No files moved."
    return "\\n".join(f"Moved {{count}} file(s) to .{{ext}}" for ext, count in sorted(result.items()))


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Organize files in a folder by extension.")
    parser.add_argument("folder", type=Path)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        print(format_result(organize_by_extension(args.folder)))
    except Exception as exc:
        print(f"Error: {{exc}}")
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def _file_organizer_test(spec: Any) -> str:
    return '''import tempfile
import unittest
from pathlib import Path

from app import organize_by_extension


class TestFileOrganizer(unittest.TestCase):
    def test_organize_files_by_extension(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            folder = Path(tmpdir)
            (folder / "a.txt").write_text("a", encoding="utf-8")
            (folder / "b.py").write_text("b", encoding="utf-8")
            result = organize_by_extension(folder)
            self.assertEqual(result["txt"], 1)
            self.assertTrue((folder / "txt" / "a.txt").exists())
            self.assertTrue((folder / "py" / "b.py").exists())


if __name__ == "__main__":
    unittest.main()
'''


def _caesar_cipher_app(spec: Any) -> str:
    request = _json(_request(spec))
    return f'''"""Caesar cipher CLI generated by BMAD."""

from __future__ import annotations

import argparse

REQUEST = {request}
ALPHABET_SIZE = 26


def shift_char(char: str, shift: int) -> str:
    if not char.isalpha():
        return char
    base = ord("A") if char.isupper() else ord("a")
    return chr((ord(char) - base + shift) % ALPHABET_SIZE + base)


def caesar_encrypt(message: str, shift: int) -> str:
    return "".join(shift_char(char, shift) for char in message)


def caesar_decrypt(message: str, shift: int) -> str:
    return caesar_encrypt(message, -shift)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Encrypt or decrypt messages with a Caesar cipher.")
    parser.add_argument("mode", choices=["encrypt", "decrypt"])
    parser.add_argument("message")
    parser.add_argument("shift", type=int)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if args.mode == "encrypt":
        print(caesar_encrypt(args.message, args.shift))
    else:
        print(caesar_decrypt(args.message, args.shift))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def _caesar_cipher_test(spec: Any) -> str:
    return '''import unittest

from app import caesar_decrypt, caesar_encrypt


class TestCaesarCipher(unittest.TestCase):
    def test_encrypt_and_decrypt(self) -> None:
        encrypted = caesar_encrypt("hello", 3)
        self.assertEqual(encrypted, "khoor")
        self.assertEqual(caesar_decrypt(encrypted, 3), "hello")

    def test_preserves_punctuation(self) -> None:
        self.assertEqual(caesar_encrypt("Hi!", 2), "Jk!")


if __name__ == "__main__":
    unittest.main()
'''


def _chatbot_memory_app(spec: Any) -> str:
    request = _json(_request(spec))
    return f'''"""Simple chatbot with memory generated by BMAD."""

from __future__ import annotations

import argparse

REQUEST = {request}


def remember(memory: dict[str, str], key: str, value: str) -> str:
    memory[key.strip().lower()] = value.strip()
    return f"Remembered {{key.strip().lower()}}."


def reply(message: str, memory: dict[str, str]) -> str:
    text = message.strip()
    lower = text.lower()
    if lower.startswith("remember ") and " is " in lower:
        payload = text[len("remember "):]
        key, value = payload.split(" is ", 1)
        return remember(memory, key, value)
    if lower.startswith("what is "):
        key = lower[len("what is "):].strip(" ?")
        return memory.get(key, "I do not know yet.")
    return "I can remember facts. Try: remember name is Elwen"


def run_scripted_chat(messages: list[str]) -> list[str]:
    memory: dict[str, str] = {{}}
    return [reply(message, memory) for message in messages]


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Run a tiny scripted chatbot with memory.")
    parser.add_argument("messages", nargs="*", help="Messages to send. If empty, runs a demo.")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    messages = args.messages or ["remember name is Elwen", "what is name?"]
    for answer in run_scripted_chat(messages):
        print(answer)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def _chatbot_memory_test(spec: Any) -> str:
    return '''import unittest

from app import reply, run_scripted_chat


class TestChatbotMemory(unittest.TestCase):
    def test_remember_and_recall(self) -> None:
        memory: dict[str, str] = {}
        self.assertIn("Remembered", reply("remember name is Elwen", memory))
        self.assertEqual(reply("what is name?", memory), "Elwen")

    def test_scripted_chat(self) -> None:
        answers = run_scripted_chat(["remember color is violet", "what is color?"])
        self.assertEqual(answers[-1], "violet")


if __name__ == "__main__":
    unittest.main()
'''


def _test_runner_app(spec: Any) -> str:
    request = _json(_request(spec))
    return f'''"""Generated-code test runner CLI generated by BMAD."""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

REQUEST = {request}


def run_unit_tests(folder: Path) -> tuple[int, str]:
    completed = subprocess.run(
        [sys.executable, "-m", "unittest", "discover", str(folder)],
        text=True,
        capture_output=True,
    )
    return completed.returncode, completed.stdout + completed.stderr


def run_manual_command(command: list[str], cwd: Path) -> tuple[int, str]:
    completed = subprocess.run(command, cwd=cwd, text=True, capture_output=True)
    return completed.returncode, completed.stdout + completed.stderr


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Run unit tests for generated Python code.")
    parser.add_argument("folder", type=Path, nargs="?", default=Path("."))
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    code, output = run_unit_tests(args.folder)
    print("Unit tests passed." if code == 0 else "Unit tests failed.")
    if output.strip():
        print(output.strip())
    return code


if __name__ == "__main__":
    raise SystemExit(main())
'''


def _test_runner_test(spec: Any) -> str:
    return '''import tempfile
import unittest
from pathlib import Path

from app import run_manual_command


class TestGeneratedTestRunner(unittest.TestCase):
    def test_manual_command_runs(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            code, output = run_manual_command(["python", "-c", "print('ok')"], Path(tmpdir))
            self.assertEqual(code, 0)
            self.assertIn("ok", output)


if __name__ == "__main__":
    unittest.main()
'''


def _calculator_app(spec: Any) -> str:
    request = _json(_request(spec))
    return f'''"""Calculator CLI generated by BMAD."""

from __future__ import annotations

import argparse

REQUEST = {request}


def calculate(operation: str, a: float, b: float) -> float:
    if operation == "add":
        return a + b
    if operation == "subtract":
        return a - b
    if operation == "multiply":
        return a * b
    if operation == "divide":
        if b == 0:
            raise ValueError("Cannot divide by zero.")
        return a / b
    raise ValueError("Unsupported operation.")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Run simple arithmetic operations.")
    parser.add_argument("operation", choices=["add", "subtract", "multiply", "divide"])
    parser.add_argument("a", type=float)
    parser.add_argument("b", type=float)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        print(f"{{calculate(args.operation, args.a, args.b):.6g}}")
    except ValueError as exc:
        print(f"Error: {{exc}}")
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def _calculator_test(spec: Any) -> str:
    return '''import unittest

from app import calculate


class TestCalculator(unittest.TestCase):
    def test_operations(self) -> None:
        self.assertEqual(calculate("add", 2, 3), 5)
        self.assertEqual(calculate("multiply", 2, 3), 6)
        self.assertEqual(calculate("divide", 6, 3), 2)

    def test_divide_by_zero(self) -> None:
        with self.assertRaises(ValueError):
            calculate("divide", 1, 0)


if __name__ == "__main__":
    unittest.main()
'''


def _text_analyzer_app(spec: Any) -> str:
    request = _json(_request(spec))
    return f'''"""Text analyzer CLI generated by BMAD."""

from __future__ import annotations

import argparse
import re

REQUEST = {request}


def analyze_text(text: str) -> dict[str, int]:
    words = re.findall(r"\\b\\w+\\b", text)
    return {{"characters": len(text), "words": len(words), "lines": text.count("\\n") + (1 if text else 0)}}


def format_analysis(stats: dict[str, int]) -> str:
    return f"characters: {{stats['characters']}}\\nwords: {{stats['words']}}\\nlines: {{stats['lines']}}"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Analyze a text string.")
    parser.add_argument("text")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    print(format_analysis(analyze_text(args.text)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def _text_analyzer_test(spec: Any) -> str:
    return '''import unittest

from app import analyze_text


class TestTextAnalyzer(unittest.TestCase):
    def test_analyze_text(self) -> None:
        stats = analyze_text("hello world")
        self.assertEqual(stats["words"], 2)
        self.assertEqual(stats["characters"], 11)


if __name__ == "__main__":
    unittest.main()
'''
