#!/usr/bin/env python3
"""Optional LLM code-generation helpers for the BMAD coding team.

This module is intentionally optional. It imports Agno and the Ollama provider
only inside ``AgnoOllamaCodeGenerator.generate`` so the deterministic BMAD
benchmarks can still run on machines where Agno, Ollama, or a local model are
not available.

Step 8 strengthens the LLM path for open-ended coding prompts. The provider now
uses a stricter implementation prompt and a quality gate that rejects placeholder
projects before they are written to ``staging/``. This keeps BMAD from accepting
"describe the project" skeletons when the user requested real behavior.
"""

from __future__ import annotations

import ast
import json
import os
import re
from dataclasses import dataclass, field
from pathlib import PurePosixPath
from typing import Any, Protocol, Sequence


@dataclass(frozen=True)
class GeneratedCodeFile:
    """One source artifact proposed by an LLM coding provider."""

    path: str
    content: str
    purpose: str = "generated file"


@dataclass(frozen=True)
class CodeGenerationResult:
    """Result returned by an optional code-generation provider."""

    success: bool
    provider: str
    summary: str
    files: list[GeneratedCodeFile] = field(default_factory=list)
    error: str | None = None
    raw_response: str | None = None
    diagnostics: list[str] = field(default_factory=list)


class LLMCodeGenerator(Protocol):
    """Small protocol used by BMAD's Dev Agent."""

    def generate(self, spec: Any) -> CodeGenerationResult: ...


_ALLOWED_FILENAMES = {
    "app.py",
    "test_app.py",
    "README.md",
    "requirements.txt",
}

_STOPWORDS = {
    "a",
    "an",
    "and",
    "app",
    "application",
    "basic",
    "build",
    "cli",
    "code",
    "create",
    "file",
    "for",
    "from",
    "generate",
    "in",
    "include",
    "make",
    "program",
    "project",
    "python",
    "readme",
    "simple",
    "small",
    "test",
    "tests",
    "that",
    "the",
    "to",
    "unit",
    "with",
}

_PLACEHOLDER_MARKERS = {
    "describe_project",
    "generated by the minimal bmad coding team",
    "build a useful generic python cli",
    "return a small structured description",
    "not implemented",
    "todo: implement",
}


# ---------------------------------------------------------------------------
# Response parsing and safety validation
# ---------------------------------------------------------------------------
def _response_to_text(response: Any) -> str:
    """Extract text from common Agno response object shapes."""

    if response is None:
        return ""
    if isinstance(response, str):
        return response
    content = getattr(response, "content", None)
    if content is not None:
        return str(content)
    message = getattr(response, "message", None)
    if isinstance(message, dict):
        content = message.get("content")
        if content is not None:
            return str(content)
    if isinstance(response, dict):
        if "content" in response:
            return str(response["content"])
        if isinstance(response.get("message"), dict):
            return str(response["message"].get("content", ""))
    return str(response)


def _extract_json_payload(text: str) -> dict[str, Any]:
    """Parse a strict JSON object, accepting markdown fenced JSON if needed."""

    text = (text or "").strip()
    if not text:
        raise ValueError("LLM returned an empty response.")

    fenced = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, flags=re.IGNORECASE | re.DOTALL)
    if fenced:
        text = fenced.group(1).strip()
    else:
        start = text.find("{")
        end = text.rfind("}")
        if start != -1 and end != -1 and end > start:
            text = text[start : end + 1]

    payload = json.loads(text)
    if not isinstance(payload, dict):
        raise ValueError("LLM JSON payload must be an object.")
    return payload


def _validate_relative_path(path: str) -> str:
    """Validate a generated path before it is written to staging/."""

    cleaned = str(path or "").replace("\\", "/").strip()
    if not cleaned:
        raise ValueError("Generated file path is empty.")
    posix = PurePosixPath(cleaned)
    if posix.is_absolute() or ".." in posix.parts:
        raise ValueError(f"Unsafe generated path rejected: {path!r}")
    if cleaned not in _ALLOWED_FILENAMES:
        raise ValueError(
            f"Generated path {cleaned!r} is not allowed in this LLM integration. "
            f"Allowed files: {sorted(_ALLOWED_FILENAMES)}"
        )
    return cleaned


def _python_syntax_errors(files: Sequence[GeneratedCodeFile]) -> list[str]:
    diagnostics: list[str] = []
    for file in files:
        if file.path.endswith(".py"):
            try:
                ast.parse(file.content, filename=file.path)
            except SyntaxError as exc:
                diagnostics.append(f"{file.path} has invalid Python syntax: {exc}")
    return diagnostics


def _request_keywords(request: str) -> set[str]:
    words = [word.lower() for word in re.findall(r"[A-Za-z][A-Za-z0-9_]{2,}", request or "")]
    keywords = {word for word in words if word not in _STOPWORDS}

    # Normalize a few common user/task terms so the quality gate catches intent
    # rather than exact spelling only.
    aliases = {
        "quadratic": {"quadratic", "equation", "roots", "discriminant", "solve"},
        "equation": {"equation", "solve", "root"},
        "password": {"password", "strength", "security"},
        "expense": {"expense", "budget", "total"},
        "todo": {"todo", "task", "list"},
        "temperature": {"temperature", "celsius", "fahrenheit"},
        "memory": {"memory", "store", "retrieve", "recall"},
        "memories": {"memory", "store", "retrieve", "recall"},
        "csv": {"csv", "statistics", "mean", "min", "max", "count"},
        "email": {"email", "validate", "valid"},
        "phone": {"phone", "validate", "valid"},
        "caesar": {"caesar", "cipher", "encrypt", "decrypt"},
        "cipher": {"cipher", "encrypt", "decrypt"},
        "chatbot": {"chatbot", "memory", "reply"},
        "organize": {"organize", "files", "extension"},
        "weather": {"weather", "data", "download", "plot"},
    }
    expanded = set(keywords)
    for word in list(keywords):
        expanded.update(aliases.get(word, set()))
    return expanded


def _function_names(app_code: str) -> set[str]:
    try:
        tree = ast.parse(app_code)
    except SyntaxError:
        return set()
    return {node.name for node in ast.walk(tree) if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))}


def _looks_like_placeholder(app_code: str, request: str) -> bool:
    lower_app = app_code.lower()
    if any(marker in lower_app for marker in _PLACEHOLDER_MARKERS):
        return True

    names = _function_names(app_code)
    if names and names <= {"describe_project", "main"}:
        # A project-description-only script is not an implementation for an
        # open-ended coding request such as solving equations or tracking data.
        request_keywords = _request_keywords(request)
        return bool(request_keywords)
    return False


def quality_gate_code_generation(result: CodeGenerationResult, spec: Any) -> CodeGenerationResult:
    """Reject unsafe or low-value LLM output before BMAD writes it to staging.

    The gate intentionally stays lightweight. It does not prove semantic
    correctness, but it blocks the most common failure mode observed with small
    local models: returning a generic ``describe_project`` skeleton instead of
    implementing the user's request.
    """

    if not result.success:
        return result

    diagnostics: list[str] = []
    diagnostics.extend(_python_syntax_errors(result.files))

    by_path = {file.path: file for file in result.files}
    app = by_path.get("app.py")
    readme = by_path.get("README.md")
    test_file = by_path.get("test_app.py")
    request = str(getattr(spec, "original_request", "") or "")
    request_lower = request.lower()

    if app is None:
        diagnostics.append("app.py is missing after parsing.")
    else:
        if _looks_like_placeholder(app.content, request):
            diagnostics.append("app.py looks like a placeholder instead of a task-specific implementation.")
        keywords = _request_keywords(request)
        if keywords:
            app_lower = app.content.lower()
            readme_lower = readme.content.lower() if readme else ""
            covered = {keyword for keyword in keywords if keyword in app_lower or keyword in readme_lower}
            # Require at least one strong intent keyword to appear in the generated
            # implementation/documentation. This catches unrelated generic output.
            if not covered:
                diagnostics.append(
                    "Generated files do not appear to cover the request keywords: "
                    + ", ".join(sorted(list(keywords))[:8])
                )

    tests_requested = any(word in request_lower for word in ["test", "tests", "unit", "unittest"])
    if tests_requested and test_file is None:
        diagnostics.append("The user requested tests, but test_app.py is missing.")
    if test_file is not None and "unittest" not in test_file.content:
        diagnostics.append("test_app.py must use unittest for the current local QA command.")

    if diagnostics:
        return CodeGenerationResult(
            success=False,
            provider=result.provider,
            summary="LLM output failed the BMAD quality gate.",
            files=[],
            error="; ".join(diagnostics),
            raw_response=result.raw_response,
            diagnostics=diagnostics,
        )

    return CodeGenerationResult(
        success=True,
        provider=result.provider,
        summary=result.summary,
        files=result.files,
        error=result.error,
        raw_response=result.raw_response,
        diagnostics=["LLM output passed BMAD safety and quality gate."],
    )


def parse_code_generation_response(raw_response: str, provider: str = "llm") -> CodeGenerationResult:
    """Convert the LLM JSON response into validated generated files."""

    try:
        payload = _extract_json_payload(raw_response)
        raw_files = payload.get("files")
        if not isinstance(raw_files, list) or not raw_files:
            raise ValueError("LLM JSON must contain a non-empty 'files' list.")

        files: list[GeneratedCodeFile] = []
        seen: set[str] = set()
        for index, item in enumerate(raw_files, start=1):
            if not isinstance(item, dict):
                raise ValueError(f"files[{index}] must be an object.")
            path = _validate_relative_path(str(item.get("path", "")))
            content = item.get("content")
            if not isinstance(content, str) or not content.strip():
                raise ValueError(f"files[{index}] has empty content.")
            if path in seen:
                raise ValueError(f"Duplicate generated path: {path}")
            seen.add(path)
            files.append(
                GeneratedCodeFile(
                    path=path,
                    content=content,
                    purpose=str(item.get("purpose") or "generated file"),
                )
            )

        required = {"app.py", "README.md"}
        missing = sorted(required - {file.path for file in files})
        if missing:
            raise ValueError(f"LLM output is missing required files: {missing}")

        summary = str(payload.get("summary") or "LLM generated code files.")
        syntax_diagnostics = _python_syntax_errors(files)
        if syntax_diagnostics:
            raise ValueError("; ".join(syntax_diagnostics))

        return CodeGenerationResult(success=True, provider=provider, summary=summary, files=files, raw_response=raw_response)
    except Exception as exc:
        return CodeGenerationResult(
            success=False,
            provider=provider,
            summary="LLM output could not be used safely.",
            files=[],
            error=str(exc),
            raw_response=raw_response,
            diagnostics=[str(exc)],
        )


# ---------------------------------------------------------------------------
# Agno/Ollama provider
# ---------------------------------------------------------------------------
class AgnoOllamaCodeGenerator:
    """Generate BMAD code artifacts with an Agno Agent backed by Ollama."""

    def __init__(
        self,
        *,
        model_name: str | None = None,
        provider_name: str = "agno_ollama",
        temperature: float = 0.0,
        markdown: bool = False,
    ) -> None:
        self.model_name = model_name or os.getenv("OLLAMA_MODEL", "llama3.2:1b")
        self.provider_name = provider_name
        self.temperature = temperature
        self.markdown = markdown

    def _import_agno(self) -> tuple[Any, Any]:
        try:
            from agno.agent import Agent  # type: ignore
        except Exception as exc:  # pragma: no cover - depends on local env
            raise RuntimeError(
                "Agno is not installed. Install/update it with: python -m pip install -U agno ollama"
            ) from exc

        try:
            from agno.models.ollama import Ollama  # type: ignore
        except Exception:
            try:
                from agno.models.ollama.chat import Ollama  # type: ignore
            except Exception as exc:  # pragma: no cover - depends on Agno version
                raise RuntimeError(
                    "Agno is installed, but the Ollama provider import path was not found. "
                    "Try: python -m pip install -U agno ollama"
                ) from exc
        return Agent, Ollama

    def build_prompt(self, spec: Any) -> str:
        requirements = "\n".join(f"- {item}" for item in getattr(spec, "requirements", []))
        criteria = "\n".join(f"- {item}" for item in getattr(spec, "acceptance_criteria", []))
        examples = "\n".join(f"- {item}" for item in getattr(spec, "cli_examples", [])) or "- python app.py"
        memory_context = getattr(spec, "memory_context", "") or "No Titan memory context provided."
        return f"""
You are the Dev Agent inside a BMAD software factory.
Generate a small, runnable Python project that REALLY implements the user's request.

Return ONLY valid JSON. Do not wrap it in prose or markdown fences.
The JSON schema is:
{{
  "summary": "one short sentence",
  "files": [
    {{"path": "app.py", "purpose": "main implementation", "content": "..."}},
    {{"path": "README.md", "purpose": "usage documentation", "content": "..."}},
    {{"path": "test_app.py", "purpose": "unittest tests", "content": "..."}}
  ]
}}

Hard rules:
- Only generate these file paths: app.py, README.md, test_app.py, requirements.txt.
- app.py and README.md are mandatory.
- Create test_app.py when tests are requested.
- Prefer Python standard library only.
- Tests must use unittest so they run with: python -m unittest test_app.py
- app.py must expose pure functions that test_app.py can import.
- app.py must also have a CLI entry point guarded by if __name__ == "__main__".
- Escape newlines correctly inside JSON strings.

Quality rules:
- Do NOT create a placeholder that only describes the project.
- Do NOT use only a describe_project() function unless the user explicitly asked for metadata only.
- Infer the domain from the request and implement actual behavior.
- Add at least one domain-specific pure function with a meaningful name.
- Add tests that verify real behavior, not only that the request string is present.
- Keep the code compact, deterministic and easy for QA to execute locally.

Examples of expected behavior:
- If the request mentions quadratic equations, implement solve_quadratic(a, b, c) with discriminant logic and CLI args a b c.
- If the request mentions user memories, implement store_memory() and retrieve_memories() with a safe local JSON file.
- If the request mentions CSV statistics, implement read_numeric_values() and calculate_statistics() with count/min/max/mean.
- If the request mentions validators, implement real validation functions such as is_valid_email() and is_valid_phone().
- If the request mentions file organization, implement safe folder scanning and movement by extension.
- If the request mentions Caesar cipher, implement encrypt/decrypt functions and test the round trip.
- If the request mentions a calculator, implement arithmetic functions and CLI operations.
- If the request mentions text analysis, implement word/character counting functions.
- If the request is outside these examples, infer the domain and implement real behavior anyway; never fall back to metadata-only code.

User request:
{getattr(spec, "original_request", "")}

Functional goal:
{getattr(spec, "goal", "")}

Requirements:
{requirements}

Acceptance criteria:
{criteria}

Suggested CLI examples:
{examples}

Read-only Titan project memory context:
{memory_context}
""".strip()

    def build_repair_prompt(
        self,
        spec: Any,
        *,
        qa_failures: Sequence[str],
        current_files: Sequence[GeneratedCodeFile],
        attempt: int,
    ) -> str:
        failures = "\n".join(f"- {failure}" for failure in qa_failures) or "- Unknown QA failure"
        files_text = "\n\n".join(
            f"### {file.path}\n```\n{file.content}\n```" for file in current_files
        ) or "No current files were available."
        return f"""
You are the Dev Agent inside a BMAD software factory.
The generated project failed QA or quality validation. Repair the files.

Return ONLY valid JSON. Do not wrap it in prose.
The JSON schema is the same as the initial generation schema:
{{
  "summary": "one short sentence describing the repair",
  "files": [
    {{"path": "app.py", "purpose": "main implementation", "content": "..."}},
    {{"path": "README.md", "purpose": "usage documentation", "content": "..."}},
    {{"path": "test_app.py", "purpose": "unittest tests", "content": "..."}}
  ]
}}

Hard rules:
- Only generate these file paths: app.py, README.md, test_app.py, requirements.txt.
- app.py and README.md are mandatory.
- Prefer Python standard library only.
- Tests must use unittest so they run with: python -m unittest test_app.py
- app.py must expose pure functions that test_app.py can import.
- app.py must also have a CLI entry point guarded by if __name__ == "__main__".
- Fix the QA failures. Do not reintroduce the same errors.
- Do not use markdown fences around the JSON.
- Do not return a generic describe_project placeholder.

Repair attempt: {attempt}

Original user request:
{getattr(spec, "original_request", "")}

Functional goal:
{getattr(spec, "goal", "")}

QA failures to fix:
{failures}

Current staged files:
{files_text}
""".strip()

    def repair(
        self,
        *,
        spec: Any,
        qa_failures: Sequence[str],
        current_files: Sequence[GeneratedCodeFile],
        attempt: int = 1,
    ) -> CodeGenerationResult:
        try:
            Agent, Ollama = self._import_agno()
            model_kwargs = {"id": self.model_name}
            try:
                model = Ollama(**model_kwargs, options={"temperature": self.temperature})
            except TypeError:
                model = Ollama(**model_kwargs)

            agent = Agent(
                name="BMAD Dev LLM Repair Agent",
                role="Repair Python project files after BMAD QA failure.",
                model=model,
                instructions=[
                    "Return only valid JSON matching the requested schema.",
                    "Do not call tools. Do not include explanations outside JSON.",
                    "Repair the implementation itself, not only the documentation.",
                ],
                markdown=self.markdown,
            )
            response = agent.run(
                self.build_repair_prompt(
                    spec,
                    qa_failures=qa_failures,
                    current_files=current_files,
                    attempt=attempt,
                )
            )
            raw_text = _response_to_text(response)
            parsed = parse_code_generation_response(raw_text, provider=f"{self.provider_name}_repair")
            return quality_gate_code_generation(parsed, spec)
        except Exception as exc:  # pragma: no cover - depends on local env
            return CodeGenerationResult(
                success=False,
                provider=f"{self.provider_name}_repair",
                summary="Agno/Ollama repair failed before producing usable files.",
                files=[],
                error=str(exc),
                raw_response=None,
                diagnostics=[str(exc)],
            )

    def generate(self, spec: Any) -> CodeGenerationResult:
        try:
            Agent, Ollama = self._import_agno()
            model_kwargs = {"id": self.model_name}
            try:
                model = Ollama(**model_kwargs, options={"temperature": self.temperature})
            except TypeError:
                model = Ollama(**model_kwargs)

            agent = Agent(
                name="BMAD Dev LLM Code Generator",
                role="Generate safe Python project files as JSON for BMAD staging.",
                model=model,
                instructions=[
                    "Return only valid JSON matching the requested schema.",
                    "Do not call tools. Do not include explanations outside JSON.",
                    "Implement the requested behavior; do not return a placeholder.",
                ],
                markdown=self.markdown,
            )
            response = agent.run(self.build_prompt(spec))
            raw_text = _response_to_text(response)
            parsed = parse_code_generation_response(raw_text, provider=self.provider_name)
            return quality_gate_code_generation(parsed, spec)
        except Exception as exc:  # pragma: no cover - depends on local env
            return CodeGenerationResult(
                success=False,
                provider=self.provider_name,
                summary="Agno/Ollama generation failed before producing usable files.",
                files=[],
                error=str(exc),
                raw_response=None,
                diagnostics=[str(exc)],
            )
