#!/usr/bin/env python3
"""Minimal BMAD-style coding team.

This is the first coding-agent orchestration prototype for the Titan memory
project. It deliberately avoids Agno, Ollama and Titan memory so the basic
software-factory workflow can be tested in isolation:

Project Manager -> Business -> Dev -> DevOps -> QA -> Evaluator

The team writes generated files to ``Test_models/staging`` through the coding
tools added in step 1, validates them, and publishes accepted output to
``Test_models/workspace``.
"""

from __future__ import annotations

import argparse
import ast
import json
import re
import sys
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Iterable, Sequence

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools.docker_tools import create_docker_compose, create_dockerfile, run_tests_in_docker
from tools.file_tools import (
    STAGING_DIR,
    WORKSPACE_DIR,
    clear_staging,
    clear_workspace,
    list_staging_files,
    list_workspace_files,
    publish_to_workspace,
    read_staging_file,
    write_file_to_staging,
)


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------
@dataclass(frozen=True)
class BMADArtifact:
    """A file generated by the Dev, Designer or DevOps step."""

    path: str
    purpose: str
    producer: str


@dataclass(frozen=True)
class BMADStep:
    """A deterministic role response in the BMAD workflow."""

    agent: str
    role: str
    summary: str
    actions: list[str] = field(default_factory=list)
    artifacts: list[BMADArtifact] = field(default_factory=list)
    status: str = "done"


@dataclass(frozen=True)
class TaskSpec:
    """Small implementation specification produced by the Business Agent."""

    original_request: str
    project_name: str
    goal: str
    requirements: list[str]
    acceptance_criteria: list[str]
    target_language: str = "python"
    entrypoint: str = "app.py"


@dataclass(frozen=True)
class QAReport:
    """QA result before the Evaluator decides whether to publish."""

    passed: bool
    checks: list[str]
    failures: list[str]
    docker_output: str | None = None


@dataclass(frozen=True)
class BMADResult:
    """Full result returned by the BMAD coding team."""

    task: str
    approved: bool
    published: bool
    publish_result: str
    workspace_files: list[str]
    staging_files_after_run: list[str]
    steps: list[BMADStep]
    qa_report: QAReport
    final_message: str

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _slugify(text: str, default: str = "generated_project") -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "_", text.strip().lower()).strip("_")
    if not slug:
        return default
    return slug[:48]


def _workspace_file_list() -> list[str]:
    if not WORKSPACE_DIR.exists():
        return []
    return sorted(
        path.relative_to(WORKSPACE_DIR).as_posix()
        for path in WORKSPACE_DIR.rglob("*")
        if path.is_file() and path.name != ".gitkeep"
    )


def _staging_file_list() -> list[str]:
    if not STAGING_DIR.exists():
        return []
    return sorted(
        path.relative_to(STAGING_DIR).as_posix()
        for path in STAGING_DIR.rglob("*")
        if path.is_file() and path.name != ".gitkeep"
    )


def _extract_title(task: str) -> str:
    words = re.findall(r"[A-Za-z0-9]+", task)
    if not words:
        return "Generated Python App"
    important = [word for word in words if len(word) > 2][:5]
    if not important:
        important = words[:5]
    return " ".join(word.capitalize() for word in important)


def _safe_python_string(text: str) -> str:
    return json.dumps(text, ensure_ascii=False)


# ---------------------------------------------------------------------------
# BMAD roles
# ---------------------------------------------------------------------------
class ProjectManagerAgent:
    name = "Project Manager"
    role = "orchestration"

    def start(self, task: str, clean_workspace: bool) -> BMADStep:
        actions = ["receive_task", "clear_staging"]
        clear_staging()
        if clean_workspace:
            clear_workspace()
            actions.append("clear_workspace")
        return BMADStep(
            agent=self.name,
            role=self.role,
            summary="Task received. Staging is clean and the BMAD workflow can start.",
            actions=actions,
        )

    def finish(self, result: BMADResult) -> BMADStep:
        status = "approved" if result.approved else "rejected"
        return BMADStep(
            agent=self.name,
            role=self.role,
            summary=(
                "Final decision: output approved and published."
                if result.published
                else "Final decision: output not published because validation failed."
            ),
            actions=["final_decision", "publish" if result.published else "request_revision"],
            status=status,
        )


class BusinessAgent:
    name = "Business Agent"
    role = "functional specification"

    def define_spec(self, task: str) -> tuple[TaskSpec, BMADStep]:
        title = _extract_title(task)
        project_name = _slugify(title)
        lower = task.lower()

        requirements = [
            "Create a small, readable Python implementation.",
            "Keep the result self-contained inside staging before validation.",
            "Include a README explaining how to run the generated code.",
        ]
        if any(word in lower for word in ["test", "pytest", "unit"]):
            requirements.append("Include a basic test file.")
        if any(word in lower for word in ["cli", "terminal", "command"]):
            requirements.append("Expose a simple command-line entry point.")

        acceptance_criteria = [
            "app.py exists in staging.",
            "README.md exists in staging.",
            "Generated Python code passes syntax validation.",
            "Evaluator approves before publishing to workspace.",
        ]

        spec = TaskSpec(
            original_request=task,
            project_name=project_name,
            goal=f"Build a minimal Python artifact for: {task}",
            requirements=requirements,
            acceptance_criteria=acceptance_criteria,
        )
        step = BMADStep(
            agent=self.name,
            role=self.role,
            summary=f"Defined a minimal functional spec for '{title}'.",
            actions=["define_goal", "define_requirements", "define_acceptance_criteria"],
        )
        return spec, step


class DevAgent:
    name = "Dev"
    role = "code generation"

    def implement(self, spec: TaskSpec) -> BMADStep:
        app_content = self._build_app(spec)
        readme_content = self._build_readme(spec)

        write_file_to_staging("app.py", app_content)
        write_file_to_staging("README.md", readme_content)

        artifacts = [
            BMADArtifact(path="app.py", purpose="Main generated Python entry point", producer=self.name),
            BMADArtifact(path="README.md", purpose="Usage and project explanation", producer=self.name),
        ]

        # If the Business Agent asked for a test, generate one. This keeps the
        # workflow deterministic but still supports test-oriented requests.
        if "Include a basic test file." in spec.requirements:
            write_file_to_staging("test_app.py", self._build_test(spec))
            artifacts.append(BMADArtifact(path="test_app.py", purpose="Basic generated unit test", producer=self.name))

        return BMADStep(
            agent=self.name,
            role=self.role,
            summary="Generated the first implementation files in staging/.",
            actions=["write_app", "write_readme"] + (["write_tests"] if len(artifacts) > 2 else []),
            artifacts=artifacts,
        )

    def _build_app(self, spec: TaskSpec) -> str:
        title = _extract_title(spec.original_request)
        goal = _safe_python_string(spec.goal)
        request = _safe_python_string(spec.original_request)
        return f'''"""Generated by the minimal BMAD coding team.

Request: {spec.original_request}
"""

from __future__ import annotations


def describe_project() -> dict[str, str]:
    """Return a small structured description of the generated project."""

    return {{
        "name": "{spec.project_name}",
        "title": "{title}",
        "request": {request},
        "goal": {goal},
    }}


def main() -> None:
    """Command-line entry point."""

    project = describe_project()
    print(f"{{project['title']}}")
    print(f"Goal: {{project['goal']}}")


if __name__ == "__main__":
    main()
'''

    def _build_readme(self, spec: TaskSpec) -> str:
        requirements = "\n".join(f"- {item}" for item in spec.requirements)
        criteria = "\n".join(f"- {item}" for item in spec.acceptance_criteria)
        return f"""# {_extract_title(spec.original_request)}

Generated by the minimal BMAD coding team.

## Original request

{spec.original_request}

## Goal

{spec.goal}

## Requirements

{requirements}

## Acceptance criteria

{criteria}

## Run

```bash
python app.py
```
"""

    def _build_test(self, spec: TaskSpec) -> str:
        return f'''from app import describe_project


def test_describe_project_contains_request() -> None:
    project = describe_project()
    assert project["name"] == "{spec.project_name}"
    assert {json.dumps(spec.original_request)} in project["request"]
'''


class DesignerAgent:
    name = "Designer"
    role = "documentation and user experience"

    def review(self, spec: TaskSpec) -> BMADStep:
        # In this minimal non-LLM version the Designer does not add complex UI,
        # but it makes sure the user-facing README exists and has clear sections.
        readme = read_staging_file("README.md")
        actions = ["review_readme"]
        status = "done"
        summary = "README structure checked for user-facing clarity."
        if "## Run" not in readme:
            status = "needs_revision"
            summary = "README is missing a run section."
        return BMADStep(agent=self.name, role=self.role, summary=summary, actions=actions, status=status)


class DevOpsAgent:
    name = "DevOps"
    role = "environment and execution"

    def prepare_environment(self) -> BMADStep:
        dockerfile = """FROM python:3.11-slim
WORKDIR /app
COPY . /app
CMD ["python", "app.py"]
"""
        compose = """services:
  app:
    build: .
"""
        create_dockerfile(dockerfile)
        create_docker_compose(compose)
        return BMADStep(
            agent=self.name,
            role=self.role,
            summary="Created Dockerfile and docker-compose.yml in staging/.",
            actions=["create_dockerfile", "create_docker_compose"],
            artifacts=[
                BMADArtifact(path="Dockerfile", purpose="Container execution recipe", producer=self.name),
                BMADArtifact(path="docker-compose.yml", purpose="Compose service definition", producer=self.name),
            ],
        )


class QAAgent:
    name = "QA"
    role = "validation"

    def validate(self, run_docker: bool = False) -> tuple[QAReport, BMADStep]:
        checks: list[str] = []
        failures: list[str] = []
        required_files = ["app.py", "README.md", "Dockerfile", "docker-compose.yml"]

        for relative_path in required_files:
            target = STAGING_DIR / relative_path
            if target.exists() and target.is_file():
                checks.append(f"Found staging/{relative_path}.")
            else:
                failures.append(f"Missing staging/{relative_path}.")

        app_path = STAGING_DIR / "app.py"
        if app_path.exists():
            try:
                ast.parse(app_path.read_text(encoding="utf-8"))
                checks.append("app.py syntax validation passed.")
            except SyntaxError as exc:
                failures.append(f"app.py syntax error: {exc}")

        test_path = STAGING_DIR / "test_app.py"
        if test_path.exists():
            try:
                ast.parse(test_path.read_text(encoding="utf-8"))
                checks.append("test_app.py syntax validation passed.")
            except SyntaxError as exc:
                failures.append(f"test_app.py syntax error: {exc}")

        docker_output: str | None = None
        if run_docker:
            docker_output = run_tests_in_docker()
            checks.append("Docker execution attempted.")
            if not docker_output.startswith("Return code: 0"):
                failures.append("Docker execution did not return code 0.")
        else:
            checks.append("Docker execution skipped for this minimal local test.")

        report = QAReport(passed=not failures, checks=checks, failures=failures, docker_output=docker_output)
        step = BMADStep(
            agent=self.name,
            role=self.role,
            summary="QA passed." if report.passed else "QA failed.",
            actions=["check_required_files", "syntax_validate"] + (["run_docker"] if run_docker else ["skip_docker"]),
            status="passed" if report.passed else "failed",
        )
        return report, step


class EvaluatorAgent:
    name = "Evaluator"
    role = "quality gate"

    def evaluate(self, spec: TaskSpec, qa_report: QAReport) -> BMADStep:
        if qa_report.passed:
            summary = "Accepted: generated artifacts satisfy the minimal BMAD acceptance criteria."
            status = "approved"
            actions = ["approve_publish"]
        else:
            summary = "Rejected: QA found blocking issues."
            status = "rejected"
            actions = ["request_revision"]
        return BMADStep(agent=self.name, role=self.role, summary=summary, actions=actions, status=status)


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------
class BMADCodingTeam:
    """Deterministic BMAD coding workflow using staging/workspace tools."""

    def __init__(self) -> None:
        self.project_manager = ProjectManagerAgent()
        self.business = BusinessAgent()
        self.dev = DevAgent()
        self.designer = DesignerAgent()
        self.devops = DevOpsAgent()
        self.qa = QAAgent()
        self.evaluator = EvaluatorAgent()

    def run(self, task: str, *, run_docker: bool = False, clean_workspace: bool = False) -> BMADResult:
        """Run the complete minimal coding workflow.

        Args:
            task: User coding request.
            run_docker: If true, QA calls Docker through ``run_tests_in_docker``.
                The default is false so this benchmark works on machines where
                Docker is not installed or not running.
            clean_workspace: If true, workspace/ is cleared before publishing.
        """

        task = (task or "").strip()
        if not task:
            raise ValueError("A non-empty coding task is required.")

        steps: list[BMADStep] = []
        steps.append(self.project_manager.start(task, clean_workspace=clean_workspace))

        spec, business_step = self.business.define_spec(task)
        steps.append(business_step)
        steps.append(self.dev.implement(spec))
        steps.append(self.designer.review(spec))
        steps.append(self.devops.prepare_environment())

        qa_report, qa_step = self.qa.validate(run_docker=run_docker)
        steps.append(qa_step)

        evaluation_step = self.evaluator.evaluate(spec, qa_report)
        steps.append(evaluation_step)

        approved = evaluation_step.status == "approved"
        if approved:
            publish_result = publish_to_workspace(useful_files=["app.py", "README.md", "test_app.py"] if (STAGING_DIR / "test_app.py").exists() else ["app.py", "README.md"])
            published = publish_result.startswith("Success:")
        else:
            publish_result = "Not published because QA/Evaluator rejected the result."
            published = False

        # Build a temporary result to let the PM create the final decision step.
        partial_result = BMADResult(
            task=task,
            approved=approved,
            published=published,
            publish_result=publish_result,
            workspace_files=_workspace_file_list(),
            staging_files_after_run=_staging_file_list(),
            steps=steps,
            qa_report=qa_report,
            final_message="",
        )
        steps.append(self.project_manager.finish(partial_result))

        workspace_files = _workspace_file_list()
        staging_files = _staging_file_list()
        final_message = self._build_final_message(task, approved, published, publish_result, workspace_files, qa_report)

        return BMADResult(
            task=task,
            approved=approved,
            published=published,
            publish_result=publish_result,
            workspace_files=workspace_files,
            staging_files_after_run=staging_files,
            steps=steps,
            qa_report=qa_report,
            final_message=final_message,
        )

    def _build_final_message(
        self,
        task: str,
        approved: bool,
        published: bool,
        publish_result: str,
        workspace_files: Sequence[str],
        qa_report: QAReport,
    ) -> str:
        status = "APPROVED" if approved else "REJECTED"
        lines = [
            f"BMAD coding workflow result: {status}",
            f"Task: {task}",
            f"Published: {published}",
            f"Publish result: {publish_result}",
            "Workspace files: " + (", ".join(workspace_files) if workspace_files else "none"),
            "QA checks:",
        ]
        lines.extend(f"- {check}" for check in qa_report.checks)
        if qa_report.failures:
            lines.append("QA failures:")
            lines.extend(f"- {failure}" for failure in qa_report.failures)
        return "\n".join(lines)


def run_bmad_task(task: str, *, run_docker: bool = False, clean_workspace: bool = False) -> BMADResult:
    """Convenience function for scripts and future agent integrations."""

    return BMADCodingTeam().run(task, run_docker=run_docker, clean_workspace=clean_workspace)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Run the minimal BMAD coding team.")
    parser.add_argument("--task", required=True, help="Coding task to execute.")
    parser.add_argument("--run-docker", action="store_true", help="Run Docker validation during QA.")
    parser.add_argument("--clean-workspace", action="store_true", help="Clear workspace before publishing.")
    parser.add_argument("--json", action="store_true", help="Print the full result as JSON.")
    args = parser.parse_args(argv)

    result = run_bmad_task(args.task, run_docker=args.run_docker, clean_workspace=args.clean_workspace)
    if args.json:
        print(json.dumps(result.to_dict(), ensure_ascii=False, indent=2))
    else:
        print(result.final_message)
    return 0 if result.approved else 1


if __name__ == "__main__":  # pragma: no cover - CLI entry point
    raise SystemExit(main())
