#!/usr/bin/env python3
"""BMAD-style coding team with optional Titan memory and optional LLM generation.

This is the coding-agent orchestration prototype for the Titan memory
project. Its default path remains deterministic so the basic software-factory
workflow can be tested locally, while Step 6 can optionally delegate code
generation to an Agno/Ollama Dev Agent:

Project Manager -> Business -> Dev -> DevOps -> QA -> Evaluator

Step 3 added a controlled Titan connection in read-only mode. The Project
Manager can retrieve relevant long-term memory before the workflow starts and
share that context with the deterministic BMAD roles.

Step 4 adds a controlled memory-validation gate. The workflow still does not
write to Titan by default. It proposes a memory candidate, the Evaluator and
Project Manager validate whether it is eligible for long-term storage, and Titan
is written only when the caller explicitly enables ``store_approved_memory``.

The team writes generated files to ``Test_models/staging`` through the coding
tools added in step 1, validates them, and publishes accepted output to
``Test_models/workspace``.

Step 7 adds an automatic repair loop: when QA fails, the Dev Agent receives the
QA failures, rewrites the staged files, and QA runs again before the Evaluator
rejects or approves the result.

Step 8 strengthens open-ended code generation: the LLM prompt now explicitly
forbids placeholder skeletons, LLM output passes a quality gate before staging,
and the deterministic fallback includes a quadratic-equation solver template.

Step 9 adds runtime behavior validation and a stricter publish filter: QA can
execute generated CLIs with expected outputs, while workspace/ receives only
important user-facing files instead of validation-only artifacts.

Step 11 improves Docker/sandbox execution: when requested, QA builds a staging
Docker image, runs generated unit tests and behavior checks inside the container,
and falls back cleanly to local validation when Docker is unavailable.
"""

from __future__ import annotations

import argparse
import ast
import json
import re
import shutil
import subprocess
import sys
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Iterable, Protocol, Sequence

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools.docker_tools import create_docker_compose, create_dockerfile, run_commands_in_docker
from agents.bmad_llm_codegen import AgnoOllamaCodeGenerator, CodeGenerationResult, GeneratedCodeFile, LLMCodeGenerator
from agents.bmad_templates import build_app_template, build_test_template
from tools.file_tools import (
    STAGING_DIR,
    WORKSPACE_DIR,
    clear_staging,
    clear_workspace,
    list_staging_files,
    list_workspace_files,
    publish_to_workspace,
    read_staging_file,
    write_file_to_staging,
)


class ReadOnlyMemory(Protocol):
    """Small protocol for read-only memory dependencies.

    TitanAgentMemory satisfies this protocol, and tests can inject a fake
    object with the same read-only methods. Write methods are intentionally not
    part of the protocol.
    """

    def load(self, path: str | Path | None = None) -> bool: ...

    def recall(self, query: str, top_k: int | None = None, min_score: float | None = None) -> list[Any]: ...


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------
@dataclass(frozen=True)
class MemoryContext:
    """Read-only memory context recovered before the BMAD workflow starts."""

    enabled: bool
    query: str
    context: str
    records: list[dict[str, Any]] = field(default_factory=list)
    loaded: bool = False
    source: str = "disabled"
    error: str | None = None

    @property
    def has_relevant_memories(self) -> bool:
        return bool(self.records)


@dataclass(frozen=True)
class MemoryValidationDecision:
    """Decision produced by the controlled memory gate.

    The candidate is validated by the Evaluator/Project Manager pair. Storage is
    allowed only when the generated result is approved and the caller explicitly
    enables the write gate. This keeps long-term Titan memory clean by default.
    """

    candidate: str | None
    should_store: bool
    stored: bool
    reason: str
    approved_by: list[str] = field(default_factory=list)
    records_stored: int = 0
    store_result: str = "not_requested"
    error: str | None = None


@dataclass(frozen=True)
class BMADArtifact:
    """A file generated by the Dev, Designer or DevOps step."""

    path: str
    purpose: str
    producer: str


@dataclass(frozen=True)
class BMADStep:
    """A deterministic role response in the BMAD workflow."""

    agent: str
    role: str
    summary: str
    actions: list[str] = field(default_factory=list)
    artifacts: list[BMADArtifact] = field(default_factory=list)
    status: str = "done"


@dataclass(frozen=True)
class BehaviorCheck:
    """Runtime CLI behavior check executed by QA.

    Unit tests validate Python functions. Behavior checks validate the generated
    command-line program as a user would run it from a terminal. Optional setup
    files/directories let QA test CLIs such as CSV readers and file organizers
    without requiring the user to prepare data manually.
    """

    name: str
    args: list[str]
    expected_returncode: int = 0
    expected_output_fragments: list[str] = field(default_factory=list)
    cleanup_files: list[str] = field(default_factory=list)
    setup_files: dict[str, str] = field(default_factory=dict)
    setup_dirs: list[str] = field(default_factory=list)
    cleanup_paths: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class TaskSpec:
    """Small implementation specification produced by the Business Agent."""

    original_request: str
    project_name: str
    goal: str
    requirements: list[str]
    acceptance_criteria: list[str]
    target_language: str = "python"
    entrypoint: str = "app.py"
    project_kind: str = "generic"
    cli_examples: list[str] = field(default_factory=list)
    test_command: str = "python -m unittest test_app.py"
    behavior_checks: list[BehaviorCheck] = field(default_factory=list)
    memory_context: str = ""
    memory_context_used: bool = False


@dataclass(frozen=True)
class QAReport:
    """QA result before the Evaluator decides whether to publish."""

    passed: bool
    checks: list[str]
    failures: list[str]
    docker_output: str | None = None
    attempt: int = 0




def _qa_repair_messages(qa_report: QAReport, max_chars: int = 5000) -> list[str]:
    """Build a compact repair context from QA failures, checks and Docker logs.

    Earlier repair cycles only sent the raw failure strings. This helper keeps
    those failures, but also includes the QA attempt number, successful checks
    and Docker diagnostics when available. The LLM repair agent can then fix the
    real cause instead of guessing from a short error fragment.
    """

    messages: list[str] = [f"QA attempt {qa_report.attempt} failed."]
    if qa_report.failures:
        messages.append("Blocking failures:")
        messages.extend(f"- {failure}" for failure in qa_report.failures)
    if qa_report.checks:
        messages.append("Checks that already passed before the failure:")
        messages.extend(f"- {check}" for check in qa_report.checks[-12:])
    if qa_report.docker_output:
        messages.append("Docker diagnostic output:")
        messages.append(qa_report.docker_output[-max_chars:])

    compact = "\n".join(messages)
    if len(compact) <= max_chars:
        return messages
    return [compact[-max_chars:]]


@dataclass(frozen=True)
class BMADResult:
    """Full result returned by the BMAD coding team."""

    task: str
    approved: bool
    published: bool
    publish_result: str
    workspace_files: list[str]
    staging_files_after_run: list[str]
    steps: list[BMADStep]
    qa_report: QAReport
    memory_context: MemoryContext
    memory_candidate: str | None
    memory_validation: MemoryValidationDecision
    final_message: str
    revision_attempts: int = 0

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _slugify(text: str, default: str = "generated_project") -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "_", text.strip().lower()).strip("_")
    if not slug:
        return default
    return slug[:48]


def _workspace_file_list() -> list[str]:
    if not WORKSPACE_DIR.exists():
        return []
    return sorted(
        path.relative_to(WORKSPACE_DIR).as_posix()
        for path in WORKSPACE_DIR.rglob("*")
        if path.is_file() and path.name != ".gitkeep"
    )


def _staging_file_list() -> list[str]:
    if not STAGING_DIR.exists():
        return []
    return sorted(
        path.relative_to(STAGING_DIR).as_posix()
        for path in STAGING_DIR.rglob("*")
        if path.is_file() and path.name != ".gitkeep"
    )


def _manual_test_commands(spec: TaskSpec | None, workspace_files: Sequence[str]) -> list[str]:
    """Build user-facing manual test commands from Test_models/."""

    if spec is None or "app.py" not in workspace_files:
        return []
    commands = [example.replace("python app.py", r"python workspace\app.py", 1) for example in spec.cli_examples]
    if "test_app.py" in workspace_files:
        commands.append(r"cd workspace; python -m unittest test_app.py; cd ..")
    return commands


def _select_publishable_files() -> list[str]:
    """Return only user-facing files that should be copied to workspace/.

    DevOps/sandbox files such as Dockerfile and docker-compose.yml are useful
    during validation, but they are not part of the minimal published artifact
    by default. requirements.txt is included only when the generator produced it.
    """

    allowlist = ["app.py", "README.md", "test_app.py", "requirements.txt"]
    return [relative for relative in allowlist if (STAGING_DIR / relative).is_file()]


def _extract_title(task: str) -> str:
    words = re.findall(r"[A-Za-z0-9]+", task)
    if not words:
        return "Generated Python App"
    important = [word for word in words if len(word) > 2][:5]
    if not important:
        important = words[:5]
    return " ".join(word.capitalize() for word in important)


def _safe_python_string(text: str) -> str:
    return json.dumps(text, ensure_ascii=False)


def _detect_project_kind(task: str) -> str:
    """Detect a deterministic implementation template for the no-LLM workflow.

    This classifier covers frequent prompts offline. For any request outside
    these patterns, the BMAD should prefer the optional LLM path. The QA gate
    later prevents unknown specific requests from being approved as a generic
    describe_project() placeholder.
    """

    lower = task.lower()
    if any(word in lower for word in ["quadratic", "second degree", "2nd degree", "discriminant", "roots"]):
        return "quadratic_solver"
    if any(word in lower for word in ["temperature", "celsius", "fahrenheit"]):
        return "temperature_converter"
    if any(word in lower for word in ["todo", "to-do", "task list", "task manager"]):
        return "todo_cli"
    if any(word in lower for word in ["user memories", "store and retrieve", "stores and retrieves", "memory store", "retrieve memories"]):
        return "memory_store"
    if "csv" in lower and any(word in lower for word in ["statistic", "statistics", "mean", "average", "calculate"]):
        return "csv_statistics"
    if any(word in lower for word in ["multi-agent", "multi agent", "agents system", "simulate agents"]):
        return "multi_agent_simulation"
    if ("email" in lower and "phone" in lower) or any(word in lower for word in ["validate email", "validates email"]):
        return "email_phone_validator"
    if any(word in lower for word in ["organizes files", "organize files", "by extension", "folder by extension"]):
        return "file_organizer"
    if any(word in lower for word in ["caesar", "cipher", "encrypt", "decrypt"]):
        return "caesar_cipher"
    if "chatbot" in lower and "memory" in lower:
        return "chatbot_with_memory"
    if any(word in lower for word in ["automatically runs manual", "test runner", "runs manual and unit tests", "run tests for generated"]):
        return "test_runner"
    if any(word in lower for word in ["password", "strength checker", "security score"]):
        return "password_strength"
    if any(word in lower for word in ["expense", "budget", "spending", "tracker"]):
        return "expense_tracker"
    if any(word in lower for word in ["calculator", "arithmetic", "add subtract", "multiply", "divide"]):
        return "calculator_cli"
    if any(word in lower for word in ["text analyzer", "text analysis", "count words", "word count", "character count"]):
        return "text_analyzer"
    return "generic"


def _request_requires_specific_implementation(task: str) -> bool:
    """Return true when a placeholder app should never be approved.

    A simple "create a CLI app" prompt can be satisfied by a tiny generic app.
    A prompt asking to solve, read, validate, organize, encrypt, simulate, etc.
    needs real behavior or a valid LLM implementation.
    """

    lower = f" {task.lower()} "
    strong_verbs = [
        " solve ", " manage ", " stores ", " store ", " retrieves ", " retrieve ",
        " read ", " calculate ", " simulates ", " simulate ", " validates ",
        " validate ", " organizes ", " organize ", " encrypts ", " encrypt ",
        " decrypts ", " decrypt ", " creates a simple chatbot", " chatbot", " runs manual",
        " automatically runs", " analyze ", " count ", " convert ", " track ",
        " download ", " downloads ", " plot ", " plots ", " fetch ", " parse ",
    ]
    domain_words = [
        "quadratic", "todo", "memory", "csv", "multi-agent", "multi agent", "email",
        "phone", "extension", "folder", "caesar", "cipher", "chatbot", "password",
        "expense", "calculator", "statistics", "file", "files", "weather", "data", "chart",
    ]
    return any(verb in lower for verb in strong_verbs) or any(word in lower for word in domain_words)


def _app_looks_like_generic_placeholder(app_code: str) -> bool:
    lower = app_code.lower()
    placeholder_markers = [
        "def describe_project",
        "return a small structured description",
        "build a useful generic python cli",
        "generated by the minimal bmad coding team",
    ]
    return any(marker in lower for marker in placeholder_markers)


def _kind_label(project_kind: str) -> str:
    labels = {
        "temperature_converter": "temperature converter CLI",
        "todo_cli": "todo-list CLI",
        "memory_store": "user memory store CLI",
        "csv_statistics": "CSV statistics CLI",
        "multi_agent_simulation": "simple multi-agent simulation CLI",
        "email_phone_validator": "email and phone validator CLI",
        "file_organizer": "file organizer by extension CLI",
        "caesar_cipher": "Caesar cipher CLI",
        "chatbot_with_memory": "chatbot with memory CLI",
        "test_runner": "generated-code test runner CLI",
        "password_strength": "password strength checker CLI",
        "expense_tracker": "expense tracker CLI",
        "quadratic_solver": "quadratic equation solver CLI",
        "calculator_cli": "calculator CLI",
        "text_analyzer": "text analyzer CLI",
        "generic": "generic Python CLI",
    }
    return labels.get(project_kind, "generic Python CLI")


def _kind_requirements(project_kind: str) -> list[str]:
    requirements_by_kind = {
        "temperature_converter": [
            "Implement Celsius to Fahrenheit conversion.",
            "Implement Fahrenheit to Celsius conversion.",
            "Expose CLI flags for both conversion directions.",
        ],
        "todo_cli": [
            "Implement add, list and clear operations for todo items.",
            "Keep todo persistence in a simple local text file by default.",
            "Expose CLI subcommands for each todo operation.",
        ],
        "memory_store": [
            "Implement store and retrieve operations for user memories.",
            "Persist memories in a small local JSON file by default.",
            "Expose CLI subcommands: store and retrieve.",
        ],
        "csv_statistics": [
            "Read a CSV file with a header row.",
            "Extract a numeric column and calculate count, min, max and mean.",
            "Expose CLI arguments for CSV path and optional column name.",
        ],
        "multi_agent_simulation": [
            "Create simple Agent objects with roles.",
            "Simulate a manager/developer/QA workflow for a task.",
            "Print a readable multi-agent execution trace.",
        ],
        "email_phone_validator": [
            "Validate email addresses with deterministic rules.",
            "Validate phone numbers with deterministic rules.",
            "Expose CLI commands for email and phone validation.",
        ],
        "file_organizer": [
            "Organize files in a folder into subfolders by extension.",
            "Use safe local filesystem operations only.",
            "Report how many files were moved per extension.",
        ],
        "caesar_cipher": [
            "Encrypt messages with a Caesar cipher shift.",
            "Decrypt messages with the same shift.",
            "Preserve non-letter characters.",
        ],
        "chatbot_with_memory": [
            "Implement a simple deterministic chatbot.",
            "Support remembering key/value facts during a scripted session.",
            "Support recalling remembered facts.",
        ],
        "test_runner": [
            "Run unit tests for generated Python code.",
            "Expose a CLI that accepts a folder path.",
            "Return the underlying test command exit code.",
        ],
        "password_strength": [
            "Analyze password length, lowercase, uppercase, digit and symbol coverage.",
            "Return a score and a human-readable strength label.",
            "Expose a CLI argument for checking one password.",
        ],
        "expense_tracker": [
            "Implement expense storage in a small JSON file by default.",
            "Implement add, list and total operations.",
            "Expose CLI subcommands for each expense operation.",
        ],
        "quadratic_solver": [
            "Implement a function to solve quadratic equations ax^2 + bx + c = 0.",
            "Handle two real roots, one repeated root, no real roots and invalid a=0 input.",
            "Expose CLI arguments for coefficients a, b and c.",
        ],
        "calculator_cli": [
            "Implement add, subtract, multiply and divide operations.",
            "Handle division by zero safely.",
            "Expose CLI arguments for operation and two numbers.",
        ],
        "text_analyzer": [
            "Count words, characters and lines in text.",
            "Expose a CLI argument for input text.",
            "Print a readable statistics report.",
        ],
    }
    return requirements_by_kind.get(project_kind, ["Expose a simple command-line entry point."])


def _kind_cli_examples(project_kind: str) -> list[str]:
    examples_by_kind = {
        "temperature_converter": ["python app.py --celsius 20", "python app.py --fahrenheit 68"],
        "todo_cli": ["python app.py add 'Write benchmark'", "python app.py list", "python app.py clear"],
        "memory_store": ["python app.py store Elwen 'favorite color is violet'", "python app.py retrieve Elwen"],
        "csv_statistics": ["python app.py sample.csv", "python app.py sample.csv --column score"],
        "multi_agent_simulation": ["python app.py 'Build a CLI feature'"],
        "email_phone_validator": ["python app.py email test@example.com", "python app.py phone +33612345678"],
        "file_organizer": ["python app.py demo_files"],
        "caesar_cipher": ["python app.py encrypt hello 3", "python app.py decrypt khoor 3"],
        "chatbot_with_memory": ["python app.py 'remember name is Elwen' 'what is name?'"],
        "test_runner": ["python app.py ."],
        "password_strength": ["python app.py 'StrongerPass123!'"],
        "expense_tracker": ["python app.py add 'Coffee' 2.50", "python app.py list", "python app.py total"],
        "quadratic_solver": ["python app.py 1 -3 2", "python app.py 1 2 5"],
        "calculator_cli": ["python app.py add 2 3", "python app.py divide 6 3"],
        "text_analyzer": ["python app.py 'hello world'"],
    }
    return examples_by_kind.get(project_kind, ["python app.py"])


def _kind_behavior_checks(project_kind: str) -> list[BehaviorCheck]:
    """Return runtime checks for generated CLIs."""

    if project_kind == "temperature_converter":
        return [
            BehaviorCheck("celsius_to_fahrenheit_cli", ["--celsius", "20"], expected_output_fragments=["68.00", "F"]),
            BehaviorCheck("fahrenheit_to_celsius_cli", ["--fahrenheit", "68"], expected_output_fragments=["20.00", "C"]),
        ]
    if project_kind == "password_strength":
        return [BehaviorCheck("strong_password_cli", ["StrongerPass123!"], expected_output_fragments=["Password strength:", "strong"])]
    if project_kind == "quadratic_solver":
        return [
            BehaviorCheck("quadratic_two_roots_cli", ["1", "-3", "2"], expected_output_fragments=["Two real roots", "1", "2"]),
            BehaviorCheck("quadratic_repeated_root_cli", ["1", "2", "1"], expected_output_fragments=["One repeated real root", "-1"]),
            BehaviorCheck("quadratic_no_real_roots_cli", ["1", "2", "5"], expected_output_fragments=["No real roots"]),
            BehaviorCheck("quadratic_invalid_a_cli", ["0", "2", "1"], expected_returncode=2, expected_output_fragments=["Error:"]),
        ]
    if project_kind == "todo_cli":
        return [
            BehaviorCheck("todo_clear_cli", ["clear"], expected_output_fragments=["cleared"]),
            BehaviorCheck("todo_add_cli", ["add", "Write tests"], expected_output_fragments=["Added item"]),
            BehaviorCheck("todo_list_cli", ["list"], expected_output_fragments=["Write tests"], cleanup_files=["todo.txt"]),
        ]
    if project_kind == "expense_tracker":
        return [
            BehaviorCheck("expense_add_cli", ["add", "Coffee", "2.50"], expected_output_fragments=["Added expense"]),
            BehaviorCheck("expense_total_cli", ["total"], expected_output_fragments=["Total:", "2.50"], cleanup_files=["expenses.json"]),
        ]
    if project_kind == "memory_store":
        return [
            BehaviorCheck("memory_store_cli", ["store", "Elwen", "favorite color is violet"], expected_output_fragments=["Stored memory"]),
            BehaviorCheck("memory_retrieve_cli", ["retrieve", "Elwen"], expected_output_fragments=["favorite color is violet"], cleanup_files=["memories.json"]),
        ]
    if project_kind == "csv_statistics":
        return [
            BehaviorCheck(
                "csv_statistics_cli",
                ["qa_sample.csv", "--column", "score"],
                expected_output_fragments=["count: 3", "min: 10.00", "max: 20.00", "mean: 15.00"],
                setup_files={"qa_sample.csv": "name,score\nAlice,10\nBob,15\nCharlie,20\n"},
                cleanup_files=["qa_sample.csv"],
            )
        ]
    if project_kind == "multi_agent_simulation":
        return [BehaviorCheck("multi_agent_cli", ["Build feature"], expected_output_fragments=["Multi-agent simulation", "Manager", "Developer", "QA"])]
    if project_kind == "email_phone_validator":
        return [
            BehaviorCheck("valid_email_cli", ["email", "test@example.com"], expected_output_fragments=["valid"]),
            BehaviorCheck("invalid_email_cli", ["email", "wrong-email"], expected_returncode=1, expected_output_fragments=["invalid"]),
            BehaviorCheck("valid_phone_cli", ["phone", "+33612345678"], expected_output_fragments=["valid"]),
            BehaviorCheck("invalid_phone_cli", ["phone", "abc123"], expected_returncode=1, expected_output_fragments=["invalid"]),
        ]
    if project_kind == "file_organizer":
        return [
            BehaviorCheck(
                "file_organizer_cli",
                ["qa_demo_files"],
                expected_output_fragments=["Moved", "txt", "py"],
                setup_files={"qa_demo_files/a.txt": "a", "qa_demo_files/b.py": "b"},
                cleanup_paths=["qa_demo_files"],
            )
        ]
    if project_kind == "caesar_cipher":
        return [
            BehaviorCheck("caesar_encrypt_cli", ["encrypt", "hello", "3"], expected_output_fragments=["khoor"]),
            BehaviorCheck("caesar_decrypt_cli", ["decrypt", "khoor", "3"], expected_output_fragments=["hello"]),
        ]
    if project_kind == "chatbot_with_memory":
        return [BehaviorCheck("chatbot_memory_cli", ["remember name is Elwen", "what is name?"], expected_output_fragments=["Remembered", "Elwen"])]
    if project_kind == "test_runner":
        return [
            BehaviorCheck(
                "test_runner_cli",
                ["qa_test_project"],
                expected_output_fragments=["Unit tests passed"],
                setup_files={
                    "qa_test_project/test_sample.py": "import unittest\n\nclass TestSample(unittest.TestCase):\n    def test_ok(self):\n        self.assertEqual(1 + 1, 2)\n\nif __name__ == '__main__':\n    unittest.main()\n"
                },
                cleanup_paths=["qa_test_project"],
            )
        ]
    if project_kind == "calculator_cli":
        return [
            BehaviorCheck("calculator_add_cli", ["add", "2", "3"], expected_output_fragments=["5"]),
            BehaviorCheck("calculator_divide_cli", ["divide", "6", "3"], expected_output_fragments=["2"]),
        ]
    if project_kind == "text_analyzer":
        return [BehaviorCheck("text_analyzer_cli", ["hello world"], expected_output_fragments=["words: 2", "characters: 11"])]
    return []


# ---------------------------------------------------------------------------
# BMAD roles
# ---------------------------------------------------------------------------
class ProjectManagerAgent:
    name = "Project Manager"
    role = "orchestration"

    def start(self, task: str, clean_workspace: bool, memory_context: MemoryContext | None = None) -> BMADStep:
        actions = ["receive_task", "clear_staging"]
        clear_staging()
        if clean_workspace:
            clear_workspace()
            actions.append("clear_workspace")

        summary = "Task received. Staging is clean and the BMAD workflow can start."
        if memory_context and memory_context.enabled:
            actions.append("retrieve_titan_memory_read_only")
            if memory_context.error:
                summary = f"Task received. Titan read-only memory retrieval failed safely: {memory_context.error}"
            elif memory_context.has_relevant_memories:
                summary = (
                    "Task received. Titan read-only memory was retrieved "
                    f"({len(memory_context.records)} relevant record(s)) before starting BMAD."
                )
            else:
                summary = "Task received. Titan read-only memory was checked; no relevant record was found."

        return BMADStep(
            agent=self.name,
            role=self.role,
            summary=summary,
            actions=actions,
        )

    def finish(self, result: BMADResult) -> BMADStep:
        status = "approved" if result.approved else "rejected"
        memory_action = "store_validated_memory" if result.memory_validation.stored else "memory_write_skipped"
        if result.memory_validation.should_store and not result.memory_validation.stored:
            memory_action = "memory_store_failed"

        if result.published:
            summary = "Final decision: output approved and published."
        else:
            summary = "Final decision: output not published because validation failed."
        summary += f" Memory gate: {result.memory_validation.reason}"

        return BMADStep(
            agent=self.name,
            role=self.role,
            summary=summary,
            actions=[
                "final_decision",
                "publish" if result.published else "request_revision",
                "validate_memory_candidate",
                memory_action,
            ],
            status=status,
        )


class BusinessAgent:
    name = "Business Agent"
    role = "functional specification"

    def define_spec(self, task: str, memory_context: MemoryContext | None = None) -> tuple[TaskSpec, BMADStep]:
        title = _extract_title(task)
        project_name = _slugify(title)
        lower = task.lower()
        memory_text = memory_context.context.lower() if memory_context and memory_context.enabled else ""
        project_kind = _detect_project_kind(task)
        kind_label = _kind_label(project_kind)

        requirements = [
            "Create a small, readable Python implementation.",
            "Keep the result self-contained inside staging before validation.",
            "Include a README explaining how to run the generated code.",
        ]
        requirements.extend(_kind_requirements(project_kind))
        if any(word in lower for word in ["test", "pytest", "unit"]) or "pytest" in memory_text or "test" in memory_text:
            requirements.append("Include a basic test file.")
        if any(word in lower for word in ["cli", "terminal", "command"]):
            if "Expose a simple command-line entry point." not in requirements:
                requirements.append("Expose a simple command-line entry point.")
        if memory_context and memory_context.enabled:
            requirements.append("Review retrieved Titan memory context in read-only mode before implementation.")

        acceptance_criteria = [
            "app.py exists in staging.",
            "README.md exists in staging.",
            "Generated Python code passes syntax validation.",
            "Generated unit tests pass locally when test_app.py is present.",
            "Generated CLI behavior checks pass when defined for the selected app type.",
            f"Generated app matches the selected template: {kind_label}.",
            "Evaluator approves before publishing to workspace.",
        ]
        if memory_context and memory_context.enabled:
            acceptance_criteria.append("Titan memory context was retrieved in read-only mode and was not modified automatically.")

        spec = TaskSpec(
            original_request=task,
            project_name=project_name,
            goal=f"Build a useful {kind_label} for: {task}",
            requirements=requirements,
            acceptance_criteria=acceptance_criteria,
            project_kind=project_kind,
            cli_examples=_kind_cli_examples(project_kind),
            behavior_checks=_kind_behavior_checks(project_kind),
            memory_context=memory_context.context if memory_context and memory_context.enabled else "",
            memory_context_used=bool(memory_context and memory_context.enabled),
        )
        step = BMADStep(
            agent=self.name,
            role=self.role,
            summary=(
                f"Defined a functional spec for a {kind_label} ('{title}')"
                + (" using read-only Titan context." if memory_context and memory_context.enabled else ".")
            ),
            actions=["define_goal", "detect_project_template", "define_requirements", "define_acceptance_criteria"]
            + (["consume_read_only_memory_context"] if memory_context and memory_context.enabled else []),
        )
        return spec, step


class DevAgent:
    name = "Dev"
    role = "code generation"

    def __init__(
        self,
        *,
        code_generator: LLMCodeGenerator | None = None,
        llm_fallback_to_template: bool = True,
    ) -> None:
        self.code_generator = code_generator
        self.llm_fallback_to_template = bool(llm_fallback_to_template)
        self.last_llm_result: CodeGenerationResult | None = None

    def implement(self, spec: TaskSpec) -> BMADStep:
        llm_failure_note: str | None = None
        if self.code_generator is not None:
            llm_step = self._implement_with_llm(spec)
            if llm_step is not None:
                return llm_step
            if self.last_llm_result and self.last_llm_result.error:
                llm_failure_note = self.last_llm_result.error
            if not self.llm_fallback_to_template:
                write_file_to_staging("README.md", self._build_llm_failure_readme(spec, llm_failure_note))
                return BMADStep(
                    agent=self.name,
                    role=self.role,
                    summary="LLM generation failed and deterministic fallback is disabled.",
                    actions=["llm_generate_code_failed", "fallback_disabled"],
                    artifacts=[BMADArtifact(path="README.md", purpose="LLM failure report", producer=self.name)],
                    status="failed",
                )

        app_content = self._build_app(spec)
        readme_content = self._build_readme(spec)

        write_file_to_staging("app.py", app_content)
        write_file_to_staging("README.md", readme_content)

        artifacts = [
            BMADArtifact(path="app.py", purpose=f"Main generated Python entry point ({_kind_label(spec.project_kind)})", producer=self.name),
            BMADArtifact(path="README.md", purpose="Usage and project explanation", producer=self.name),
        ]

        # If the Business Agent asked for a test, generate a runnable unittest
        # file. This gives QA a real local test command without requiring pytest.
        if "Include a basic test file." in spec.requirements:
            write_file_to_staging("test_app.py", self._build_test(spec))
            artifacts.append(BMADArtifact(path="test_app.py", purpose="Basic generated unittest file", producer=self.name))

        actions = ["select_code_template", "write_app", "write_readme"] + (["write_tests"] if len(artifacts) > 2 else [])
        summary = f"Generated a {_kind_label(spec.project_kind)} implementation in staging/."
        if llm_failure_note:
            actions = ["llm_generate_code_failed", "fallback_to_deterministic_template", *actions]
            summary = "LLM generation failed safely; deterministic template fallback was used."

        return BMADStep(
            agent=self.name,
            role=self.role,
            summary=summary,
            actions=actions,
            artifacts=artifacts,
        )

    def repair(self, spec: TaskSpec, qa_report: QAReport, attempt: int) -> BMADStep:
        """Repair staged files after QA failure.

        The first strategy asks the optional LLM provider to repair the current
        staged project when it exposes a ``repair`` method. If that is not
        available, or if the provider returns unsafe output, the Dev Agent
        rewrites the project from the deterministic safe template. This keeps
        the loop useful with Agno/Ollama while remaining fully testable offline.
        """

        if self.code_generator is not None and hasattr(self.code_generator, "repair"):
            llm_step = self._repair_with_llm(spec, qa_report, attempt)
            if llm_step is not None:
                return llm_step

        app_content = self._build_app(spec)
        readme_content = self._build_readme(spec)
        write_file_to_staging("app.py", app_content)
        write_file_to_staging("README.md", readme_content)

        artifacts = [
            BMADArtifact(path="app.py", purpose="Repaired main Python entry point", producer=self.name),
            BMADArtifact(path="README.md", purpose="Repaired usage documentation", producer=self.name),
        ]
        if "Include a basic test file." in spec.requirements:
            write_file_to_staging("test_app.py", self._build_test(spec))
            artifacts.append(BMADArtifact(path="test_app.py", purpose="Repaired unittest file", producer=self.name))

        repair_messages = _qa_repair_messages(qa_report)
        failures = "; ".join(repair_messages) if repair_messages else "unknown QA failure"
        return BMADStep(
            agent=self.name,
            role=self.role,
            summary=f"Repair cycle {attempt}: deterministic safe rewrite after QA/Docker diagnostics: {failures[:180]}",
            actions=["inspect_qa_diagnostics", "repair_with_deterministic_template", "rewrite_staging_files"],
            artifacts=artifacts,
        )

    def _implement_with_llm(self, spec: TaskSpec) -> BMADStep | None:
        assert self.code_generator is not None
        result = self.code_generator.generate(spec)
        self.last_llm_result = result
        if not result.success:
            return None

        artifacts: list[BMADArtifact] = []
        for file in result.files:
            write_file_to_staging(file.path, file.content)
            artifacts.append(BMADArtifact(path=file.path, purpose=file.purpose, producer=self.name))

        return BMADStep(
            agent=self.name,
            role=self.role,
            summary=f"Generated project files through {result.provider}: {result.summary}",
            actions=["llm_generate_code", "validate_llm_file_paths", "write_llm_files"],
            artifacts=artifacts,
        )

    def _repair_with_llm(self, spec: TaskSpec, qa_report: QAReport, attempt: int) -> BMADStep | None:
        assert self.code_generator is not None
        repair = getattr(self.code_generator, "repair", None)
        if repair is None:
            return None

        try:
            result = repair(
                spec=spec,
                qa_failures=_qa_repair_messages(qa_report),
                current_files=self._read_current_staging_files(),
                attempt=attempt,
            )
        except TypeError:
            return None
        except Exception as exc:
            self.last_llm_result = CodeGenerationResult(
                success=False,
                provider="llm_repair",
                summary="LLM repair failed before producing usable files.",
                error=str(exc),
            )
            return None

        self.last_llm_result = result
        if not isinstance(result, CodeGenerationResult) or not result.success:
            return None

        artifacts: list[BMADArtifact] = []
        for file in result.files:
            write_file_to_staging(file.path, file.content)
            artifacts.append(BMADArtifact(path=file.path, purpose=file.purpose, producer=self.name))

        return BMADStep(
            agent=self.name,
            role=self.role,
            summary=f"Repair cycle {attempt}: repaired project files through {result.provider}: {result.summary}",
            actions=["inspect_qa_failures", "llm_repair_code", "validate_llm_file_paths", "write_repaired_llm_files"],
            artifacts=artifacts,
        )

    @staticmethod
    def _read_current_staging_files() -> list[GeneratedCodeFile]:
        files: list[GeneratedCodeFile] = []
        for path in ["app.py", "README.md", "test_app.py", "requirements.txt"]:
            target = STAGING_DIR / path
            if target.exists() and target.is_file():
                files.append(GeneratedCodeFile(path=path, content=target.read_text(encoding="utf-8"), purpose="current staged file"))
        return files

    def _build_llm_failure_readme(self, spec: TaskSpec, error: str | None) -> str:
        return f"""# LLM generation failed

The BMAD Dev Agent attempted to use the configured LLM provider but could not produce safe generated files.

## Original request

{spec.original_request}

## Error

{error or 'Unknown LLM generation error.'}
"""

    def _build_app(self, spec: TaskSpec) -> str:
        extended_template = build_app_template(spec.project_kind, spec)
        if extended_template is not None:
            return extended_template
        if spec.project_kind == "temperature_converter":
            return self._build_temperature_app(spec)
        if spec.project_kind == "todo_cli":
            return self._build_todo_app(spec)
        if spec.project_kind == "password_strength":
            return self._build_password_app(spec)
        if spec.project_kind == "expense_tracker":
            return self._build_expense_app(spec)
        if spec.project_kind == "quadratic_solver":
            return self._build_quadratic_app(spec)
        return self._build_generic_app(spec)

    def _build_generic_app(self, spec: TaskSpec) -> str:
        title = _extract_title(spec.original_request)
        goal = _safe_python_string(spec.goal)
        request = _safe_python_string(spec.original_request)
        return f'''"""Generated by the minimal BMAD coding team.

Request: {spec.original_request}
"""

from __future__ import annotations


def describe_project() -> dict[str, str]:
    """Return a small structured description of the generated project."""

    return {{
        "name": "{spec.project_name}",
        "title": "{title}",
        "request": {request},
        "goal": {goal},
    }}


def main() -> None:
    """Command-line entry point."""

    project = describe_project()
    print(f"{{project['title']}}")
    print(f"Goal: {{project['goal']}}")


if __name__ == "__main__":
    main()
'''

    def _build_temperature_app(self, spec: TaskSpec) -> str:
        request = _safe_python_string(spec.original_request)
        return f'''"""Temperature converter CLI generated by the BMAD coding team.

Request: {spec.original_request}
"""

from __future__ import annotations

import argparse

REQUEST = {request}


def celsius_to_fahrenheit(celsius: float) -> float:
    """Convert Celsius to Fahrenheit."""

    return (celsius * 9 / 5) + 32


def fahrenheit_to_celsius(fahrenheit: float) -> float:
    """Convert Fahrenheit to Celsius."""

    return (fahrenheit - 32) * 5 / 9


def format_temperature(value: float, unit: str) -> str:
    """Format a temperature with two decimals and a unit."""

    return f"{{value:.2f}} °{{unit}}"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Convert temperatures between Celsius and Fahrenheit.")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--celsius", type=float, help="Temperature in Celsius to convert to Fahrenheit.")
    group.add_argument("--fahrenheit", type=float, help="Temperature in Fahrenheit to convert to Celsius.")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if args.celsius is not None:
        print(format_temperature(celsius_to_fahrenheit(args.celsius), "F"))
    else:
        print(format_temperature(fahrenheit_to_celsius(args.fahrenheit), "C"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''

    def _build_todo_app(self, spec: TaskSpec) -> str:
        request = _safe_python_string(spec.original_request)
        return f'''"""Todo-list CLI generated by the BMAD coding team.

Request: {spec.original_request}
"""

from __future__ import annotations

import argparse
from pathlib import Path

REQUEST = {request}
DEFAULT_TODO_FILE = Path("todo.txt")


def load_items(path: Path = DEFAULT_TODO_FILE) -> list[str]:
    """Load todo items from a text file."""

    if not path.exists():
        return []
    return [line.strip() for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def save_items(items: list[str], path: Path = DEFAULT_TODO_FILE) -> None:
    """Save todo items to a text file."""

    path.write_text("\\n".join(items) + ("\\n" if items else ""), encoding="utf-8")


def add_item(text: str, path: Path = DEFAULT_TODO_FILE) -> list[str]:
    """Add one todo item and return the updated list."""

    item = text.strip()
    if not item:
        raise ValueError("Todo item cannot be empty.")
    items = load_items(path)
    items.append(item)
    save_items(items, path)
    return items


def clear_items(path: Path = DEFAULT_TODO_FILE) -> None:
    """Remove all todo items."""

    if path.exists():
        path.unlink()


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Manage a small local todo list.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    add_parser = subparsers.add_parser("add", help="Add a todo item.")
    add_parser.add_argument("text", help="Todo item text.")

    subparsers.add_parser("list", help="List todo items.")
    subparsers.add_parser("clear", help="Clear all todo items.")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if args.command == "add":
        items = add_item(args.text)
        print(f"Added item #{{len(items)}}: {{args.text}}")
    elif args.command == "list":
        items = load_items()
        if not items:
            print("No todo items.")
        for index, item in enumerate(items, start=1):
            print(f"{{index}}. {{item}}")
    elif args.command == "clear":
        clear_items()
        print("Todo list cleared.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''

    def _build_password_app(self, spec: TaskSpec) -> str:
        request = _safe_python_string(spec.original_request)
        return f'''"""Password strength checker CLI generated by the BMAD coding team.

Request: {spec.original_request}
"""

from __future__ import annotations

import argparse
import string

REQUEST = {request}


def analyze_password(password: str) -> dict[str, object]:
    """Return a simple strength analysis for a password."""

    checks = {{
        "length_at_least_8": len(password) >= 8,
        "has_lowercase": any(char.islower() for char in password),
        "has_uppercase": any(char.isupper() for char in password),
        "has_digit": any(char.isdigit() for char in password),
        "has_symbol": any(char in string.punctuation for char in password),
    }}
    score = sum(1 for passed in checks.values() if passed)
    if score <= 2:
        label = "weak"
    elif score <= 4:
        label = "medium"
    else:
        label = "strong"
    return {{"score": score, "label": label, "checks": checks}}


def build_report(password: str) -> str:
    result = analyze_password(password)
    return f"Password strength: {{result['label']}} ({{result['score']}}/5)"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Check password strength with simple deterministic rules.")
    parser.add_argument("password", help="Password to analyze.")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    print(build_report(args.password))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''

    def _build_expense_app(self, spec: TaskSpec) -> str:
        request = _safe_python_string(spec.original_request)
        return f'''"""Expense tracker CLI generated by the BMAD coding team.

Request: {spec.original_request}
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

REQUEST = {request}
DEFAULT_EXPENSE_FILE = Path("expenses.json")


def load_expenses(path: Path = DEFAULT_EXPENSE_FILE) -> list[dict[str, float | str]]:
    """Load expenses from a JSON file."""

    if not path.exists():
        return []
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise ValueError("Expense file must contain a list.")
    return data


def save_expenses(expenses: list[dict[str, float | str]], path: Path = DEFAULT_EXPENSE_FILE) -> None:
    """Save expenses to a JSON file."""

    path.write_text(json.dumps(expenses, indent=2), encoding="utf-8")


def add_expense(description: str, amount: float, path: Path = DEFAULT_EXPENSE_FILE) -> list[dict[str, float | str]]:
    """Add one expense and return all expenses."""

    if amount < 0:
        raise ValueError("Expense amount cannot be negative.")
    expenses = load_expenses(path)
    expenses.append({{"description": description.strip(), "amount": float(amount)}})
    save_expenses(expenses, path)
    return expenses


def total_expenses(expenses: list[dict[str, float | str]]) -> float:
    """Return the total amount for all expenses."""

    return sum(float(item["amount"]) for item in expenses)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Track simple local expenses.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    add_parser = subparsers.add_parser("add", help="Add an expense.")
    add_parser.add_argument("description", help="Expense description.")
    add_parser.add_argument("amount", type=float, help="Expense amount.")

    subparsers.add_parser("list", help="List expenses.")
    subparsers.add_parser("total", help="Show total expenses.")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if args.command == "add":
        expenses = add_expense(args.description, args.amount)
        print(f"Added expense #{{len(expenses)}}: {{args.description}} = {{args.amount:.2f}}")
    elif args.command == "list":
        for index, item in enumerate(load_expenses(), start=1):
            print(f"{{index}}. {{item['description']}} - {{float(item['amount']):.2f}}")
    elif args.command == "total":
        print(f"Total: {{total_expenses(load_expenses()):.2f}}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''

    def _build_quadratic_app(self, spec: TaskSpec) -> str:
        request = _safe_python_string(spec.original_request)
        return f'''"""Quadratic equation solver CLI generated by the BMAD coding team.

Request: {spec.original_request}
"""

from __future__ import annotations

import argparse
import math

REQUEST = {request}


def discriminant(a: float, b: float, c: float) -> float:
    """Return the discriminant for ax^2 + bx + c = 0."""

    return (b * b) - (4 * a * c)


def solve_quadratic(a: float, b: float, c: float) -> tuple[float, ...]:
    """Solve ax^2 + bx + c = 0 and return real roots.

    Returns:
        A tuple with two roots, one repeated root, or an empty tuple when there
        are no real roots.

    Raises:
        ValueError: if a is zero, because the equation is not quadratic.
    """

    if a == 0:
        raise ValueError("Coefficient a must not be zero for a quadratic equation.")
    delta = discriminant(a, b, c)
    if delta < 0:
        return ()
    if delta == 0:
        return (-b / (2 * a),)
    sqrt_delta = math.sqrt(delta)
    root1 = (-b - sqrt_delta) / (2 * a)
    root2 = (-b + sqrt_delta) / (2 * a)
    return (root1, root2)


def format_roots(roots: tuple[float, ...]) -> str:
    """Format roots for CLI display."""

    if not roots:
        return "No real roots."
    if len(roots) == 1:
        return f"One repeated real root: {{roots[0]:.6g}}"
    return f"Two real roots: {{roots[0]:.6g}} and {{roots[1]:.6g}}"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Solve a quadratic equation ax^2 + bx + c = 0.")
    parser.add_argument("a", type=float, help="Coefficient a, must be non-zero.")
    parser.add_argument("b", type=float, help="Coefficient b.")
    parser.add_argument("c", type=float, help="Coefficient c.")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        roots = solve_quadratic(args.a, args.b, args.c)
    except ValueError as exc:
        print(f"Error: {{exc}}")
        return 2
    print(format_roots(roots))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''

    def _build_readme(self, spec: TaskSpec) -> str:
        requirements = "\n".join(f"- {item}" for item in spec.requirements)
        criteria = "\n".join(f"- {item}" for item in spec.acceptance_criteria)
        cli_examples = "\n".join(f"```bash\n{example}\n```" for example in spec.cli_examples)
        memory_section = ""
        if spec.memory_context_used:
            memory_section = (
                "\n## Project memory\n\n"
                "Titan long-term memory was reviewed in read-only mode before implementation. "
                "No memory write was performed automatically.\n"
            )

        test_section = ""
        if "Include a basic test file." in spec.requirements:
            test_section = f"""
## Test

```bash
{spec.test_command}
```
"""

        return f"""# {_extract_title(spec.original_request)}

Generated by the minimal BMAD coding team.

## Selected template

{_kind_label(spec.project_kind)}

## Original request

{spec.original_request}

## Goal

{spec.goal}

## Requirements

{requirements}

## Acceptance criteria

{criteria}
{memory_section}
## Run

{cli_examples}
{test_section}"""

    def _build_test(self, spec: TaskSpec) -> str:
        extended_template = build_test_template(spec.project_kind, spec)
        if extended_template is not None:
            return extended_template
        if spec.project_kind == "temperature_converter":
            return '''import unittest

from app import celsius_to_fahrenheit, fahrenheit_to_celsius, format_temperature


class TestTemperatureConverter(unittest.TestCase):
    def test_celsius_to_fahrenheit(self) -> None:
        self.assertAlmostEqual(celsius_to_fahrenheit(0), 32.0)
        self.assertAlmostEqual(celsius_to_fahrenheit(100), 212.0)

    def test_fahrenheit_to_celsius(self) -> None:
        self.assertAlmostEqual(fahrenheit_to_celsius(32), 0.0)
        self.assertAlmostEqual(fahrenheit_to_celsius(212), 100.0)

    def test_format_temperature(self) -> None:
        self.assertEqual(format_temperature(68, "F"), "68.00 °F")


if __name__ == "__main__":
    unittest.main()
'''
        if spec.project_kind == "todo_cli":
            return '''import tempfile
import unittest
from pathlib import Path

from app import add_item, clear_items, load_items


class TestTodoCli(unittest.TestCase):
    def test_add_and_clear_items(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            path = Path(tmpdir) / "todo.txt"
            add_item("Write tests", path)
            add_item("Run QA", path)
            self.assertEqual(load_items(path), ["Write tests", "Run QA"])
            clear_items(path)
            self.assertEqual(load_items(path), [])


if __name__ == "__main__":
    unittest.main()
'''
        if spec.project_kind == "password_strength":
            return '''import unittest

from app import analyze_password, build_report


class TestPasswordStrength(unittest.TestCase):
    def test_strong_password(self) -> None:
        result = analyze_password("StrongerPass123!")
        self.assertEqual(result["label"], "strong")
        self.assertEqual(result["score"], 5)

    def test_weak_password(self) -> None:
        result = analyze_password("abc")
        self.assertEqual(result["label"], "weak")

    def test_report_contains_label(self) -> None:
        self.assertIn("Password strength:", build_report("StrongerPass123!"))


if __name__ == "__main__":
    unittest.main()
'''
        if spec.project_kind == "expense_tracker":
            return '''import tempfile
import unittest
from pathlib import Path

from app import add_expense, load_expenses, total_expenses


class TestExpenseTracker(unittest.TestCase):
    def test_add_and_total_expenses(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            path = Path(tmpdir) / "expenses.json"
            expenses = add_expense("Coffee", 2.5, path)
            expenses = add_expense("Lunch", 12.0, path)
            self.assertEqual(len(load_expenses(path)), 2)
            self.assertAlmostEqual(total_expenses(expenses), 14.5)


if __name__ == "__main__":
    unittest.main()
'''
        if spec.project_kind == "quadratic_solver":
            return '''import unittest

from app import discriminant, format_roots, solve_quadratic


class TestQuadraticSolver(unittest.TestCase):
    def test_two_real_roots(self) -> None:
        self.assertEqual(solve_quadratic(1, -3, 2), (1.0, 2.0))

    def test_repeated_root(self) -> None:
        self.assertEqual(solve_quadratic(1, 2, 1), (-1.0,))

    def test_no_real_roots(self) -> None:
        self.assertEqual(solve_quadratic(1, 2, 5), ())

    def test_invalid_a(self) -> None:
        with self.assertRaises(ValueError):
            solve_quadratic(0, 2, 1)

    def test_format_roots(self) -> None:
        self.assertIn("Two real roots", format_roots((1.0, 2.0)))
        self.assertEqual(discriminant(1, -3, 2), 1)


if __name__ == "__main__":
    unittest.main()
'''
        return f'''import unittest

from app import describe_project


class TestGeneratedProject(unittest.TestCase):
    def test_describe_project_contains_request(self) -> None:
        project = describe_project()
        self.assertEqual(project["name"], "{spec.project_name}")
        self.assertIn({json.dumps(spec.original_request)}, project["request"])


if __name__ == "__main__":
    unittest.main()
'''


class DesignerAgent:

    name = "Designer"
    role = "documentation and user experience"

    def review(self, spec: TaskSpec) -> BMADStep:
        # In this minimal non-LLM version the Designer does not add complex UI,
        # but it makes sure the user-facing README exists and has clear sections.
        readme = read_staging_file("README.md")
        actions = ["review_readme"]
        status = "done"
        summary = "README structure checked for user-facing clarity."
        if "## Run" not in readme:
            status = "needs_revision"
            summary = "README is missing a run section."
        return BMADStep(agent=self.name, role=self.role, summary=summary, actions=actions, status=status)


class DevOpsAgent:
    name = "DevOps"
    role = "environment and execution"

    def prepare_environment(self) -> BMADStep:
        dockerfile = """FROM python:3.11-slim
WORKDIR /app
COPY . /app
RUN if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi
CMD ["python", "-m", "unittest", "test_app.py"]
"""
        compose = """services:
  app:
    build: .
    working_dir: /app
    command: ["python", "-m", "unittest", "test_app.py"]
"""
        create_dockerfile(dockerfile)
        create_docker_compose(compose)
        return BMADStep(
            agent=self.name,
            role=self.role,
            summary="Created a Python test Dockerfile and docker-compose.yml in staging/.",
            actions=["create_dockerfile", "create_docker_compose", "prepare_sandbox_test_command"],
            artifacts=[
                BMADArtifact(path="Dockerfile", purpose="Containerized Python test environment", producer=self.name),
                BMADArtifact(path="docker-compose.yml", purpose="Compose test service definition", producer=self.name),
            ],
        )


class QAAgent:
    name = "QA"
    role = "validation"

    def validate(self, spec: TaskSpec | None = None, run_docker: bool = False, attempt: int = 0) -> tuple[QAReport, BMADStep]:
        checks: list[str] = []
        failures: list[str] = []
        required_files = ["app.py", "README.md", "Dockerfile", "docker-compose.yml"]

        for relative_path in required_files:
            target = STAGING_DIR / relative_path
            if target.exists() and target.is_file():
                checks.append(f"Found staging/{relative_path}.")
            else:
                failures.append(f"Missing staging/{relative_path}.")

        app_path = STAGING_DIR / "app.py"
        if app_path.exists():
            try:
                app_code = app_path.read_text(encoding="utf-8")
                ast.parse(app_code)
                checks.append("app.py syntax validation passed.")
                if spec is not None and _app_looks_like_generic_placeholder(app_code):
                    if spec.project_kind != "generic" or _request_requires_specific_implementation(spec.original_request):
                        failures.append(
                            "Generated app.py is a generic placeholder for a request that needs task-specific behavior."
                        )
            except SyntaxError as exc:
                failures.append(f"app.py syntax error: {exc}")

        test_path = STAGING_DIR / "test_app.py"
        if test_path.exists():
            test_syntax_ok = False
            try:
                ast.parse(test_path.read_text(encoding="utf-8"))
                checks.append("test_app.py syntax validation passed.")
                test_syntax_ok = True
            except SyntaxError as exc:
                failures.append(f"test_app.py syntax error: {exc}")

            if test_syntax_ok:
                try:
                    completed = subprocess.run(
                        [sys.executable, "-m", "unittest", "test_app.py"],
                        cwd=STAGING_DIR,
                        text=True,
                        capture_output=True,
                        timeout=20,
                    )
                    checks.append("Generated unit tests executed locally.")
                    if completed.returncode == 0:
                        checks.append("Generated unit tests passed locally.")
                    else:
                        failures.append(
                            "Generated unit tests failed locally: "
                            + (completed.stdout + completed.stderr).strip()[:800]
                        )
                except Exception as exc:
                    failures.append(f"Generated unit tests could not be executed locally: {exc}")

        if spec is not None and spec.behavior_checks:
            for behavior in spec.behavior_checks:
                completed = None
                try:
                    for setup_dir in behavior.setup_dirs:
                        (STAGING_DIR / setup_dir).mkdir(parents=True, exist_ok=True)
                    for relative_path, content in behavior.setup_files.items():
                        setup_path = STAGING_DIR / relative_path
                        setup_path.parent.mkdir(parents=True, exist_ok=True)
                        setup_path.write_text(content, encoding="utf-8")

                    completed = subprocess.run(
                        [sys.executable, "app.py", *behavior.args],
                        cwd=STAGING_DIR,
                        text=True,
                        capture_output=True,
                        timeout=20,
                    )
                    combined_output = (completed.stdout + completed.stderr).strip()
                    if completed.returncode != behavior.expected_returncode:
                        failures.append(
                            f"Behavior check '{behavior.name}' returned {completed.returncode}, "
                            f"expected {behavior.expected_returncode}: {combined_output[:500]}"
                        )
                        continue
                    missing = [fragment for fragment in behavior.expected_output_fragments if fragment not in combined_output]
                    if missing:
                        failures.append(
                            f"Behavior check '{behavior.name}' output missing {missing}: {combined_output[:500]}"
                        )
                    else:
                        checks.append(f"Behavior check '{behavior.name}' passed.")
                except Exception as exc:
                    failures.append(f"Behavior check '{behavior.name}' could not run: {exc}")
                finally:
                    for cleanup in behavior.cleanup_files:
                        cleanup_path = STAGING_DIR / cleanup
                        if cleanup_path.exists() and cleanup_path.is_file():
                            cleanup_path.unlink()
                    for cleanup in behavior.cleanup_paths:
                        cleanup_path = STAGING_DIR / cleanup
                        if cleanup_path.exists():
                            if cleanup_path.is_dir():
                                shutil.rmtree(cleanup_path)
                            else:
                                cleanup_path.unlink()
        elif spec is not None:
            checks.append("No runtime behavior checks defined for this app type.")

        docker_output: str | None = None
        if run_docker:
            docker_commands: list[tuple[str, list[str]]] = []
            docker_expectations: dict[str, tuple[int, list[str]]] = {}

            if test_path.exists():
                docker_commands.append(("docker_unit_tests", ["python", "-m", "unittest", "test_app.py"]))
                docker_expectations["docker_unit_tests"] = (0, [])
            else:
                docker_commands.append(("docker_import_app", ["python", "-c", "import app; print('app import ok')"]))
                docker_expectations["docker_import_app"] = (0, ["app import ok"])

            if spec is not None and spec.behavior_checks:
                try:
                    for behavior in spec.behavior_checks:
                        for setup_dir in behavior.setup_dirs:
                            (STAGING_DIR / setup_dir).mkdir(parents=True, exist_ok=True)
                        for relative_path, content in behavior.setup_files.items():
                            setup_path = STAGING_DIR / relative_path
                            setup_path.parent.mkdir(parents=True, exist_ok=True)
                            setup_path.write_text(content, encoding="utf-8")
                        docker_commands.append((behavior.name, ["python", "app.py", *behavior.args]))
                        docker_expectations[behavior.name] = (
                            behavior.expected_returncode,
                            list(behavior.expected_output_fragments),
                        )

                    docker_result = run_commands_in_docker(docker_commands)
                    docker_output = docker_result.to_text()
                    if docker_result.skipped:
                        checks.append(f"Docker execution skipped: {docker_result.reason} Local QA fallback already ran.")
                    elif not docker_result.success:
                        checks.append("Docker execution attempted in isolated sandbox.")
                        if docker_result.build_returncode not in (None, 0):
                            failures.append("Docker image build failed: " + docker_result.reason)
                        for command_result in docker_result.commands:
                            expected_code, expected_fragments = docker_expectations.get(command_result.name, (0, []))
                            combined_output = command_result.output
                            if command_result.returncode != expected_code:
                                failures.append(
                                    f"Docker check '{command_result.name}' returned {command_result.returncode}, "
                                    f"expected {expected_code}: {combined_output[:500]}"
                                )
                                continue
                            missing = [fragment for fragment in expected_fragments if fragment not in combined_output]
                            if missing:
                                failures.append(
                                    f"Docker check '{command_result.name}' output missing {missing}: {combined_output[:500]}"
                                )
                            else:
                                checks.append(f"Docker check '{command_result.name}' passed.")
                    else:
                        checks.append("Docker execution attempted in isolated sandbox.")
                        checks.append("Docker image build passed.")
                        for command_result in docker_result.commands:
                            expected_code, expected_fragments = docker_expectations.get(command_result.name, (0, []))
                            combined_output = command_result.output
                            missing = [fragment for fragment in expected_fragments if fragment not in combined_output]
                            if command_result.returncode == expected_code and not missing:
                                checks.append(f"Docker check '{command_result.name}' passed.")
                            else:
                                failures.append(
                                    f"Docker check '{command_result.name}' failed: returncode={command_result.returncode}, "
                                    f"expected={expected_code}, missing={missing}, output={combined_output[:500]}"
                                )
                finally:
                    if spec is not None:
                        for behavior in spec.behavior_checks:
                            for cleanup in behavior.cleanup_files:
                                cleanup_path = STAGING_DIR / cleanup
                                if cleanup_path.exists() and cleanup_path.is_file():
                                    cleanup_path.unlink()
                            for cleanup in behavior.cleanup_paths:
                                cleanup_path = STAGING_DIR / cleanup
                                if cleanup_path.exists():
                                    if cleanup_path.is_dir():
                                        shutil.rmtree(cleanup_path)
                                    else:
                                        cleanup_path.unlink()
        else:
            checks.append("Docker execution skipped for this minimal local test.")

        report = QAReport(passed=not failures, checks=checks, failures=failures, docker_output=docker_output, attempt=attempt)
        summary_prefix = f"QA attempt {attempt}" if attempt else "QA"
        step = BMADStep(
            agent=self.name,
            role=self.role,
            summary=(f"{summary_prefix} passed." if report.passed else f"{summary_prefix} failed."),
            actions=["check_required_files", "syntax_validate", "run_generated_unit_tests", "run_behavior_checks"] + (["run_docker"] if run_docker else ["skip_docker"]),
            status="passed" if report.passed else "failed",
        )
        return report, step


class EvaluatorAgent:
    name = "Evaluator"
    role = "quality gate"

    def evaluate(self, spec: TaskSpec, qa_report: QAReport) -> BMADStep:
        if qa_report.passed:
            summary = "Accepted: generated artifacts satisfy the minimal BMAD acceptance criteria."
            status = "approved"
            actions = ["approve_publish"]
        else:
            summary = "Rejected: QA found blocking issues."
            status = "rejected"
            actions = ["request_revision"]
        return BMADStep(agent=self.name, role=self.role, summary=summary, actions=actions, status=status)

    def validate_memory_candidate(
        self,
        *,
        candidate: str | None,
        approved: bool,
        published: bool,
        qa_report: QAReport,
        store_approved_memory: bool,
    ) -> MemoryValidationDecision:
        """Apply the controlled long-term memory write policy.

        The policy is deliberately conservative: only approved, published and
        QA-passing outputs may be stored, and even then only when the caller
        explicitly enables the write gate.
        """

        if not candidate:
            return MemoryValidationDecision(
                candidate=candidate,
                should_store=False,
                stored=False,
                reason="No memory candidate was produced.",
                store_result="skipped_no_candidate",
            )
        if not store_approved_memory:
            return MemoryValidationDecision(
                candidate=candidate,
                should_store=False,
                stored=False,
                reason="Memory write disabled; candidate proposed only.",
                approved_by=[self.name, "Project Manager"],
                store_result="skipped_write_disabled",
            )
        if not approved or not published or not qa_report.passed:
            return MemoryValidationDecision(
                candidate=candidate,
                should_store=False,
                stored=False,
                reason="Memory candidate rejected because the workflow was not fully approved, published and QA-passing.",
                approved_by=[self.name, "Project Manager"],
                store_result="skipped_not_validated",
            )
        return MemoryValidationDecision(
            candidate=candidate,
            should_store=True,
            stored=False,
            reason="Memory candidate approved for storage by Evaluator and Project Manager.",
            approved_by=[self.name, "Project Manager"],
            store_result="approved_pending_store",
        )


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------
class BMADCodingTeam:
    """Deterministic BMAD coding workflow using staging/workspace tools.

    Titan memory is optional. By default it is read-only: only ``load`` and
    ``recall`` are used. Step 4 can store a validated memory candidate only when
    the caller explicitly enables ``store_approved_memory``.
    """

    def __init__(
        self,
        *,
        memory: ReadOnlyMemory | None = None,
        use_titan_memory: bool = False,
        memory_path: str | Path | None = None,
        memory_top_k: int = 5,
        memory_min_score: float = 0.12,
        store_approved_memory: bool = False,
        code_generator: LLMCodeGenerator | None = None,
        use_llm: bool = False,
        llm_provider: str = "agno_ollama",
        ollama_model: str | None = None,
        llm_fallback_to_template: bool = True,
        max_revision_cycles: int = 1,
    ) -> None:
        self.project_manager = ProjectManagerAgent()
        self.business = BusinessAgent()
        self.code_generator = code_generator
        self.use_llm = bool(use_llm or code_generator is not None)
        self.llm_provider = llm_provider
        self.ollama_model = ollama_model
        if self.code_generator is None and self.use_llm:
            self.code_generator = self._build_code_generator(llm_provider=llm_provider, ollama_model=ollama_model)
        self.dev = DevAgent(
            code_generator=self.code_generator,
            llm_fallback_to_template=llm_fallback_to_template,
        )
        self.designer = DesignerAgent()
        self.devops = DevOpsAgent()
        self.qa = QAAgent()
        self.evaluator = EvaluatorAgent()
        self.memory = memory
        self._memory_injected = memory is not None
        self.store_approved_memory = bool(store_approved_memory)
        self.use_titan_memory = bool(use_titan_memory or memory is not None or self.store_approved_memory)
        self.memory_path = Path(memory_path) if memory_path is not None else Path("agent_titan_memory.pt")
        self.memory_top_k = int(memory_top_k)
        self.memory_min_score = float(memory_min_score)
        self.max_revision_cycles = max(0, int(max_revision_cycles))

    @staticmethod
    def _build_code_generator(*, llm_provider: str, ollama_model: str | None) -> LLMCodeGenerator:
        normalized = (llm_provider or "agno_ollama").strip().lower()
        if normalized in {"agno", "agno_ollama", "ollama"}:
            return AgnoOllamaCodeGenerator(model_name=ollama_model, provider_name="agno_ollama")
        raise ValueError(f"Unsupported BMAD LLM provider: {llm_provider!r}")

    def run(self, task: str, *, run_docker: bool = False, clean_workspace: bool = False) -> BMADResult:
        """Run the complete minimal coding workflow.

        Args:
            task: User coding request.
            run_docker: If true, QA calls Docker through ``run_tests_in_docker``.
                The default is false so this benchmark works on machines where
                Docker is not installed or not running.
            clean_workspace: If true, workspace/ is cleared before publishing.
        """

        task = (task or "").strip()
        if not task:
            raise ValueError("A non-empty coding task is required.")

        memory_context = self._retrieve_memory_context(task)

        steps: list[BMADStep] = []
        steps.append(self.project_manager.start(task, clean_workspace=clean_workspace, memory_context=memory_context))

        spec, business_step = self.business.define_spec(task, memory_context=memory_context)
        steps.append(business_step)
        steps.append(self.dev.implement(spec))
        steps.append(self.designer.review(spec))
        steps.append(self.devops.prepare_environment())

        qa_report, qa_step = self._run_qa(spec=spec, run_docker=run_docker, attempt=0)
        steps.append(qa_step)

        revision_attempts = 0
        while not qa_report.passed and revision_attempts < self.max_revision_cycles:
            revision_attempts += 1
            steps.append(self.dev.repair(spec, qa_report, revision_attempts))
            steps.append(self.designer.review(spec))
            steps.append(self.devops.prepare_environment())
            qa_report, qa_step = self._run_qa(spec=spec, run_docker=run_docker, attempt=revision_attempts)
            steps.append(qa_step)

        evaluation_step = self.evaluator.evaluate(spec, qa_report)
        steps.append(evaluation_step)

        approved = evaluation_step.status == "approved"
        if approved:
            publish_result = publish_to_workspace(useful_files=_select_publishable_files())
            published = publish_result.startswith("Success:")
        else:
            publish_result = "Not published because QA/Evaluator rejected the result."
            published = False

        memory_candidate = self._build_memory_candidate(
            task=task,
            approved=approved,
            published=published,
            workspace_files=_workspace_file_list(),
            qa_report=qa_report,
            revision_attempts=revision_attempts,
        )
        memory_validation = self.evaluator.validate_memory_candidate(
            candidate=memory_candidate,
            approved=approved,
            published=published,
            qa_report=qa_report,
            store_approved_memory=self.store_approved_memory,
        )
        if memory_validation.should_store:
            memory_validation = self._store_validated_memory(memory_validation)

        # Build a temporary result to let the PM create the final decision step.
        partial_result = BMADResult(
            task=task,
            approved=approved,
            published=published,
            publish_result=publish_result,
            workspace_files=_workspace_file_list(),
            staging_files_after_run=_staging_file_list(),
            steps=steps,
            qa_report=qa_report,
            memory_context=memory_context,
            memory_candidate=memory_candidate,
            memory_validation=memory_validation,
            final_message="",
            revision_attempts=revision_attempts,
        )
        steps.append(self.project_manager.finish(partial_result))

        workspace_files = _workspace_file_list()
        staging_files = _staging_file_list()
        final_message = self._build_final_message(
            task,
            approved,
            published,
            publish_result,
            workspace_files,
            qa_report,
            memory_context,
            memory_candidate,
            memory_validation,
            revision_attempts,
            spec,
        )

        return BMADResult(
            task=task,
            approved=approved,
            published=published,
            publish_result=publish_result,
            workspace_files=workspace_files,
            staging_files_after_run=staging_files,
            steps=steps,
            qa_report=qa_report,
            memory_context=memory_context,
            memory_candidate=memory_candidate,
            memory_validation=memory_validation,
            final_message=final_message,
            revision_attempts=revision_attempts,
        )

    def _run_qa(self, *, spec: TaskSpec, run_docker: bool, attempt: int) -> tuple[QAReport, BMADStep]:
        """Run QA while staying compatible with simple test doubles.

        Older benchmarks may replace ``qa.validate`` with a tiny function that
        only accepts ``run_docker``. The production QA accepts ``spec`` and
        ``attempt`` so it can run app-specific behavior checks and produce clear
        retry reports.
        """

        try:
            return self.qa.validate(spec=spec, run_docker=run_docker, attempt=attempt)
        except TypeError as first_exc:
            try:
                return self.qa.validate(run_docker=run_docker, attempt=attempt)
            except TypeError:
                try:
                    return self.qa.validate(run_docker=run_docker)
                except TypeError:
                    raise first_exc

    def _get_memory(self) -> ReadOnlyMemory:
        """Return the configured read-only memory object, creating Titan lazily."""

        if self.memory is not None:
            return self.memory

        # Lazy import keeps the default no-memory workflow light and avoids
        # importing PyTorch/Titan unless the caller explicitly asks for memory.
        from agents.titan_agent_memory import TitanAgentMemory

        self.memory = TitanAgentMemory(
            memory_path=self.memory_path,
            top_k=self.memory_top_k,
            min_score=self.memory_min_score,
        )
        return self.memory

    def _retrieve_memory_context(self, task: str) -> MemoryContext:
        """Retrieve Titan memory context without writing to long-term memory."""

        if not self.use_titan_memory:
            return MemoryContext(
                enabled=False,
                query=task,
                context="Titan memory read-only retrieval is disabled for this run.",
                source="disabled",
            )

        try:
            memory = self._get_memory()
            loaded = False
            if hasattr(memory, "load"):
                loaded = bool(memory.load())

            raw_records = memory.recall(task, top_k=self.memory_top_k, min_score=self.memory_min_score)
            records = [self._memory_record_to_dict(record) for record in raw_records]
            context = self._format_memory_context(records)
            source = "injected_memory" if self._memory_injected else str(self.memory_path)
            return MemoryContext(
                enabled=True,
                query=task,
                context=context,
                records=records,
                loaded=loaded,
                source=source,
            )
        except Exception as exc:  # pragma: no cover - defensive path
            return MemoryContext(
                enabled=True,
                query=task,
                context="Titan memory retrieval failed safely. Continuing without memory context.",
                records=[],
                loaded=False,
                source=str(self.memory_path),
                error=str(exc),
            )

    @staticmethod
    def _memory_record_to_dict(record: Any) -> dict[str, Any]:
        if isinstance(record, dict):
            return dict(record)
        data: dict[str, Any] = {}
        for key in ["id", "text", "score", "subject", "property", "active", "metadata"]:
            if hasattr(record, key):
                data[key] = getattr(record, key)
        if not data:
            data["text"] = str(record)
        if "text" in data:
            data["text"] = str(data["text"])
        if "score" in data:
            try:
                data["score"] = float(data["score"])
            except (TypeError, ValueError):
                data["score"] = 0.0
        return data

    @staticmethod
    def _format_memory_context(records: Sequence[dict[str, Any]]) -> str:
        if not records:
            return "No relevant long-term Titan memory found."
        lines = ["Relevant long-term Titan memories (read-only):"]
        for idx, record in enumerate(records, start=1):
            score = record.get("score", 1.0)
            subject = record.get("subject") or "?"
            prop = record.get("property") or "?"
            text = record.get("text", "")
            try:
                score_text = f"{float(score):.3f}"
            except (TypeError, ValueError):
                score_text = "?"
            lines.append(f"{idx}. [score={score_text}; subject={subject}; property={prop}] {text}")
        return "\n".join(lines)

    @staticmethod
    def _build_memory_candidate(
        *,
        task: str,
        approved: bool,
        published: bool,
        workspace_files: Sequence[str],
        qa_report: QAReport,
        revision_attempts: int = 0,
    ) -> str:
        status = "approved" if approved else "rejected"
        files = ", ".join(workspace_files) if workspace_files else "none"
        qa_status = "passed" if qa_report.passed else "failed"
        return (
            "Candidate memory only; do not store automatically. "
            f"BMAD coding workflow {status} task={task!r}; "
            f"published={published}; workspace_files={files}; QA={qa_status}; "
            f"revision_attempts={revision_attempts}."
        )

    def _store_validated_memory(self, decision: MemoryValidationDecision) -> MemoryValidationDecision:
        """Store an approved memory candidate through the controlled write gate."""

        if not decision.should_store or not decision.candidate:
            return decision
        try:
            memory = self._get_memory()
            if not hasattr(memory, "store"):
                return MemoryValidationDecision(
                    candidate=decision.candidate,
                    should_store=True,
                    stored=False,
                    reason=decision.reason,
                    approved_by=decision.approved_by,
                    records_stored=0,
                    store_result="failed_missing_store_method",
                    error="Configured memory object does not expose store().",
                )
            records = memory.store(
                decision.candidate,
                metadata={
                    "source": "bmad_coding_team",
                    "validation": "project_manager_evaluator_gate",
                    "store_policy": "explicit_store_approved_memory",
                },
            )
            try:
                records_stored = len(records)
            except TypeError:
                records_stored = 1
            if hasattr(memory, "save"):
                memory.save()
            return MemoryValidationDecision(
                candidate=decision.candidate,
                should_store=True,
                stored=True,
                reason=decision.reason,
                approved_by=decision.approved_by,
                records_stored=records_stored,
                store_result="stored_and_saved",
            )
        except Exception as exc:  # pragma: no cover - defensive path
            return MemoryValidationDecision(
                candidate=decision.candidate,
                should_store=True,
                stored=False,
                reason=decision.reason,
                approved_by=decision.approved_by,
                records_stored=0,
                store_result="failed_exception",
                error=str(exc),
            )

    def _build_final_message(
        self,
        task: str,
        approved: bool,
        published: bool,
        publish_result: str,
        workspace_files: Sequence[str],
        qa_report: QAReport,
        memory_context: MemoryContext,
        memory_candidate: str | None,
        memory_validation: MemoryValidationDecision,
        revision_attempts: int = 0,
        spec: TaskSpec | None = None,
    ) -> str:
        status = "APPROVED" if approved else "REJECTED"
        lines = [
            f"BMAD coding workflow result: {status}",
            f"Task: {task}",
            f"Published: {published}",
            f"Publish result: {publish_result}",
            f"Revision attempts: {revision_attempts}",
            "Workspace files: " + (", ".join(workspace_files) if workspace_files else "none"),
            (
                f"Titan memory read-only: enabled, records={len(memory_context.records)}, source={memory_context.source}"
                if memory_context.enabled
                else "Titan memory read-only: disabled"
            ),
            "QA checks:",
        ]
        lines.extend(f"- {check}" for check in qa_report.checks)
        if qa_report.failures:
            lines.append("QA failures:")
            lines.extend(f"- {failure}" for failure in qa_report.failures)
            if qa_report.docker_output:
                lines.append("Docker diagnostics available for repair loop:")
                lines.append(qa_report.docker_output[-1200:])
        manual_commands = _manual_test_commands(spec, workspace_files)
        if manual_commands:
            lines.append("Manual test commands:")
            lines.extend(f"- {command}" for command in manual_commands)
        if memory_candidate:
            lines.append("Memory candidate (not stored automatically):")
            lines.append(memory_candidate)
        lines.append("Memory validation:")
        lines.append(f"- should_store: {memory_validation.should_store}")
        lines.append(f"- stored: {memory_validation.stored}")
        lines.append(f"- reason: {memory_validation.reason}")
        lines.append(f"- store_result: {memory_validation.store_result}")
        if memory_validation.error:
            lines.append(f"- error: {memory_validation.error}")
        return "\n".join(lines)


def run_bmad_task(
    task: str,
    *,
    run_docker: bool = False,
    clean_workspace: bool = False,
    use_titan_memory: bool = False,
    memory_path: str | Path | None = None,
    memory_top_k: int = 5,
    memory_min_score: float = 0.12,
    store_approved_memory: bool = False,
    use_llm: bool = False,
    llm_provider: str = "agno_ollama",
    ollama_model: str | None = None,
    llm_fallback_to_template: bool = True,
    max_revision_cycles: int = 1,
) -> BMADResult:
    """Convenience function for scripts and future agent integrations."""

    return BMADCodingTeam(
        use_titan_memory=use_titan_memory,
        memory_path=memory_path,
        memory_top_k=memory_top_k,
        memory_min_score=memory_min_score,
        store_approved_memory=store_approved_memory,
        use_llm=use_llm,
        llm_provider=llm_provider,
        ollama_model=ollama_model,
        llm_fallback_to_template=llm_fallback_to_template,
        max_revision_cycles=max_revision_cycles,
    ).run(task, run_docker=run_docker, clean_workspace=clean_workspace)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Run the minimal BMAD coding team.")
    parser.add_argument("--task", required=True, help="Coding task to execute.")
    parser.add_argument("--run-docker", action="store_true", help="Run Docker validation during QA.")
    parser.add_argument("--clean-workspace", action="store_true", help="Clear workspace before publishing.")
    parser.add_argument("--use-titan-memory", action="store_true", help="Retrieve Titan memory in read-only mode before BMAD starts.")
    parser.add_argument("--memory-path", default="agent_titan_memory.pt", help="Titan memory file to read when --use-titan-memory is enabled.")
    parser.add_argument("--memory-top-k", type=int, default=5, help="Number of Titan memories to retrieve.")
    parser.add_argument("--memory-min-score", type=float, default=0.12, help="Minimum Titan retrieval score.")
    parser.add_argument("--store-approved-memory", action="store_true", help="Store the validated BMAD memory candidate in Titan. Disabled by default.")
    parser.add_argument("--use-llm", action="store_true", help="Use an optional Agno/Ollama Dev Agent for code generation, with deterministic fallback enabled.")
    parser.add_argument("--llm-provider", default="agno_ollama", help="LLM provider for BMAD Dev generation. Currently: agno_ollama.")
    parser.add_argument("--ollama-model", default=None, help="Ollama model for Agno generation. Defaults to OLLAMA_MODEL or llama3.2:1b.")
    parser.add_argument("--disable-llm-fallback", action="store_true", help="Reject the workflow if LLM generation fails instead of using deterministic templates.")
    parser.add_argument("--max-revisions", type=int, default=1, help="Maximum automatic repair cycles after QA failure. Default: 1.")
    parser.add_argument("--json", action="store_true", help="Print the full result as JSON.")
    args = parser.parse_args(argv)

    result = run_bmad_task(
        args.task,
        run_docker=args.run_docker,
        clean_workspace=args.clean_workspace,
        use_titan_memory=args.use_titan_memory,
        memory_path=args.memory_path,
        memory_top_k=args.memory_top_k,
        memory_min_score=args.memory_min_score,
        store_approved_memory=args.store_approved_memory,
        use_llm=args.use_llm,
        llm_provider=args.llm_provider,
        ollama_model=args.ollama_model,
        llm_fallback_to_template=not args.disable_llm_fallback,
        max_revision_cycles=args.max_revisions,
    )
    if args.json:
        print(json.dumps(result.to_dict(), ensure_ascii=False, indent=2))
    else:
        print(result.final_message)
    return 0 if result.approved else 1


if __name__ == "__main__":  # pragma: no cover - CLI entry point
    raise SystemExit(main())
